### ISSUE TITLE
look into async APIs

### ISSUE THREAD

**Issue by brockallen** [brockallen/BrockAllen.MembershipReboot#156]
Would anyone really be interested in async APIs for everything?

**Comment by nonnb** [comment]
+1

**Comment by brockallen** [comment]
If I were to do this, it would most likely be done as a new DNX style project with a major version change (which is a breaking change).

**Comment by huysentruitw** [comment]
Why not add ...Async variants?

**Comment by brockallen** [comment]
Perhaps...

**Comment by mplatoff** [comment]
+1

**Comment by eric-swann-q2** [comment]
+1

**Comment by immanuel-rekursv** [comment]
+1
