### ISSUE TITLE
Sending Email configuration

### ISSUE THREAD

**Issue by WilliamDoman** [brockallen/BrockAllen.MembershipReboot#213]
I'm having trouble with email.  I've tried v6

When a new user is created, it stores the user in the data store and returns from userAccountService.CreateAccount just fine, but no email is ever sent and I cant seem to get it to ever jump into the smtpmessagedelivery class.

If i manually send an email from the configuration class it works fine so I know the configs are correct.

``` C#
var delivery = new SmtpMessageDelivery();
delivery.Send(new Message() { Body = "Test", To = "me@gmail.com", Subject = "Subject" });
```

I've tried various combinations from the samples with no luck.

Any ideas would be appreciated.

from the custom sample

``` C#
var emailFormatter = new CustomEmailMessageFormatter(appinfo);
 config.AddEventHandler(new EmailAccountEventsHandler<HierarchicalUserAccount>(emailFormatter, delivery));
```

from the nosql sample

``` C#
var emailFormatter = new EmailMessageFormatter<HierarchicalUserAccount>(appinfo);
 // uncomment if you want email notifications -- also update smtp settings in web.config
config.AddEventHandler(new EmailAccountEventsHandler<HierarchicalUserAccount>(emailFormatter));
```

**Comment by juanonsoftware** [comment]
I got the same problem today, but it's due to security issue, the port is not open to Gmail on my environment :)
