### ISSUE TITLE
JSON Web Token (JWT) sample

### ISSUE THREAD

**Issue by jamesholcomb** [brockallen/BrockAllen.MembershipReboot#222]
Is there a sample you can reference or provide showing OWIN configuration using MR with JWT bearer tokens instead of cookies?

**Comment by DavidRogersDev** [comment]
Does one need to add anything server-side to permit CORS? My attempts to hit the token endpoint from a different domain are failing. The js is:
    var headers = {
        'Access-Control-Request-Method': 'POST',
        'Origin': 'http://localhost:54437/',
        'Access-Control-Request-Headers': 'origin, content-type, accept'
    };

    $.ajax({
        type: "POST",
        url: 'http://localhost:5034/token',
        data: JSON.stringify({ userName: 'alice', password: 'pass' }),
        contentType: 'application/json',
        headers: headers
    }).done(function (data) {
        
    });

I've also enabled CORS on the HttpConfiguration object at the server:
config.EnableCors();

There's no rush on getting back to me. Only if you have time.
Cheers

**Comment by brockallen** [comment]
@DavidRogersDev Of course. Look into the Cors OWIN middleware.

**Comment by DavidRogersDev** [comment]
Thanks Brock.
