### ISSUE TITLE
Request a second email when registering

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#330]
Feature request, when creating a new account, request a secondary email address that can be used in case the primary email becomes inaccessible.  What we see are members who use a company email, then quit or leave that company.  Now they forget their password.  They trigger a forgot password action but the email goes to an inbox they no longer have access to.  At least if they had say a GMail account as their backup address, they can still receive the password reset/reminder.

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
