### ISSUE TITLE
SingleTenantOwin and Customization

### ISSUE THREAD

**Issue by marius-stanescu** [brockallen/BrockAllen.MembershipReboot#349]
I impemented SingleTenantOwin and everything worked fine. After I implemented custom user account class, user repository, and db context (as in the Customizations sample), when I try to register a new account, I get the following error:

```
The source query for this EntityCollection or EntityReference cannot be returned when the related object is in either an added state or a detached state and was not originally retrieved using the NoTracking merge option.
```

on the line

```
var account = _userAccountService.CreateAccount(null, model.Password, model.Email);
```

Have I done something wrong?

**Comment by sheam** [comment]
Making 'FirstName' and 'LastName' virtual fixed the issue for me too.

**Comment by brockallen** [comment]
Ah yes -- that's a common issue. Thanks for the reminder.
