### ISSUE TITLE
Email Verification using just key?

### ISSUE THREAD

**Issue by paheal** [brockallen/BrockAllen.MembershipReboot#354]
I'm attempting to use email verification in my web application's registration process and am using the latest NuGet packages to do so. 

I'm using the SingleTenant sample as a guide, but I've hit a snag. I'd like to verify an account/email using just the key provided. In the UserAccountService, all the VerifyEmailFromKey methods eventually need the password if one was defined during  Create Account.

Is there a way to do the verification using just the key? I'm trying to avoid the need for the user to enter a password to verify their email address.

Thanks in Advance.

**Comment by cloudybrain** [comment]
I really wish I can override this functionality.. my company doesn't do self service membership, the admin is the one that takes care of everything. They are the ones responsible for the creating of users, passwords, etc. I have rarely seen any current website where a user would have to confirm an account by typing in the same password after the account has been created. It's usually one of two options:

Sent to a page that says "Confirmation success.. proceed to login"
or "Please enter in new password"

This enforced solution has gotten everyone annoyed.

**Comment by brockallen** [comment]
> I have rarely seen any current website where a user would have to confirm an account by typing in the same password after the account has been created.

And that's a potential security flaw. That's why this library requires it for the self-registration flows.

> my company doesn't do self service membership, the admin is the one that takes care of everything.

Have you considered using the `SetConfirmedEmail` API then?

> This enforced solution has gotten everyone annoyed.

Sorry, security is hard.

**Comment by cloudybrain** [comment]
Well I'm not sure how much of a security flaw it would be if the admin and the client already has a close connection. The current security flaw is that they'd have to email the password to the user they created the account for. So I decided to remove the feature of including an password.

When an admin creates a user, they only enter the user's email. A password is automatically entered hardcoded behind the scenes. This password will never be known by the admin or the actual client. So I had to edit the IdentityManager directly to automatically include this private password.

Client receives an email with a link to reset their password. The code uses GetByVerificationKey. When they sign in, and select a new password. The old password on the MembershipReboot end will be the actual password the admin used (without his knowledge), and all the user has to do is enter in their new password. When they change their password, I used the method: SetConfirmedEmail, to set the user as verified.

This will never work as long as they get the email with the confirmationkey, which is what I used in the previous method: GetByVerificationKey.

Though this is more streamlined, I don't think this exposes any extra security flaws. As long as the workflow is: admin creates and maintains all users.. then users confirm by reset password as a response, this should be fine.

Yes.. security is hard, but I'm not giving you guys any flack for this project, it's an impressive solution, and I'm learning to love it more and more.

**Comment by brockallen** [comment]
The security flaw is if the email is incorrect or entered as a typo. The incorrect recipient can now pwn potentially the account (via password reset). Requiring re-entering the password with the confirmation key ensures that the email matches the user who provided the initial password. This, of course, is only possible with user self-registration, but that's how to protect the user from themselves. 

For admin-created accounts, it's a similar concern, but you don't have a good way to mitigate it. Hopefully the email is correct and is not sent to the wrong person. Also, for these admin-created accounts if you don't want the same notifications that are sent for self-registration then I'd suggest using a different MR Config with different event registration. Not sure if that's part of your complaint. Finally, I think what you could do is use `SetConfirmedEmail` when you create the account, then trigger the password reset -- this would just allow them to come in and set a new password.

**Comment by cloudybrain** [comment]
I think this problem is okay for them. We have a bunch of authorization rules that gets followed up when they successfully log in and confirm. admin and clients have a close knit relationship. This kind of security flaw is definitely something that might happen whenever any admin creates a user.

I am also definitely using an integrated MR config for admin, with custom built emails. And yes, the SetConfirmedEmail is being triggered, but because of the new work flow of having their account confirmed when they reset the password, the "required password reset" doesn't need to be triggered. The email requests the user reset their password in order for their account to be confirmed :)
