### ISSUE TITLE
Requirement for parameterless constructor for custom DbContext

### ISSUE THREAD

**Issue by christianacca** [brockallen/BrockAllen.MembershipReboot#358]
Hi Brock,

I'm trying to enforce some _mandatory_ authorization logic to run when SaveChanges is called on the DbContext. To do this my custom DbContext declares a constructor which takes an authorization service as a parameter. 

The problem is that MR enforces a generic constraint such that any custom DbContext must also declare a _parameterless_ constructor.

OK, I could probably just throw a InvalidOperation exception indicating that the authorization service has not been supplied, but this is less explicit than just enforcing the mandatory dependency as a constructor parameter.

What's making matters worse for me is that my IoC container seems to be always favouring the parameterless constructor! Anyway to cut to the chase, any chance in removing the new() generic type constraint and using reflection instead to create the DbContext where you need to?

Thanks
Christian

**Comment by ccrowhurstram** [comment]
Just taken the update! Thanks Brock
