### ISSUE TITLE
Email not being created/sent

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#372]
The emails were working at one time and no are not. If I register a new account or use the reset password, no email is sent.  I even changed my web.config to save to disk to rule out network issues.

```
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <specifiedPickupDirectory pickupDirectoryLocation="D:\temp" />
      </smtp>
    </mailSettings>
```

I enabled trace in the web.config but no trace appears.  Since no errors occur, but the success message does display, any ideas how I can fix?

**Comment by apuchkov** [comment]
Config sample above is **missing "from" attribute**, so emails won't be sent silently!

It should be:
```
<mailSettings>
    <smtp deliveryMethod="SpecifiedPickupDirectory" from="no-reply@mydomain.com">
        <specifiedPickupDirectory pickupDirectoryLocation="D:\temp" />
    </smtp>
</mailSettings>
```

Otherwise this exception is thrown (can be seen only in a trace log):
```
[SmtpMessageDelivery.Send] Exception: Value cannot be null. Parameter name: from
```
