### ISSUE TITLE
Using DateTimeOffset instead of DateTime (Neo4j store)

### ISSUE THREAD

**Issue by assimoes** [brockallen/BrockAllen.MembershipReboot#388]
Hello guys, I've recently been implementing a Neo4j store for the User Accounts and stumbled across a problem regarding DateTime data type. Neo4j unfortunately doesn't support DateTime, so when I create a UserAccount, it's saved in the backend with the DateTimeOffset data type. The problem is when you need to deserialize that record, the Neo4jClient throws an exception.

I was able to workaround this problem by changing the UserAccount abstract class to use DateTimeOffset instead of DateTime.

Being that this would likely not be a problem with every other store, would it be ok to make this change in the master branch?

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
