### ISSUE TITLE
Resend Email Verify Message and Link

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#408]
Does anyone have sample code of how to regenerate and resend the email verification message and link?  When a user loses/deletes their verify email or lets it expire we need to be able to go into the admin and create/send a new one.

I see methods to resend mobile code, etc. but nothing for email code.

**Comment by stevenfirstrowinc** [comment]
@brockallen does this still work for 8.2.1?  I'm calling UserAccountService.SetRequiresPasswordReset but get no email

**Comment by stevenfirstrowinc** [comment]
@brockallen  nevermind I guess there is a method RequestAccountVerification.  sorry about that

**Comment by skbelalmd** [comment]
I think there is an issue with RequestAccountVerification api.
It is not sending any e-mail.

**Comment by galenp** [comment]
I'm actually encountering this just now also, but figured it was more than likely a configuration issue. The fact @skbelalmd has hit this at the same time tho... 

So assuming SMTP is correctly configured.

```c#
 //Create Account
var service = new UserAccountService<RelationalUserAccount>(userAccountRepository);
var userId = Guid.NewGuid();

service.CreateAccount(registration.Email, registration.Password, registration.Email, userId);
service.AddClaim(userId, "name", displayName);
service.AddClaim(userId, "email", registration.Email);

if (!string.IsNullOrEmpty(registration.Mobile))
    service.AddClaim(userId, "mobile", registration.Mobile);

if (!string.IsNullOrEmpty(registration.Company))
    service.AddClaim(userId, "company", registration.Company);

service.RequestAccountVerification(userId);	
```
Am I correct to assume there is no more additional configuration required for the 'default' verification emails to be sent by MR to the email address of the new account?

I do understand that the URL's contained within these emails would be incorrect for my implementation.

**Comment by galenp** [comment]
Sorry Brock, just realised how old this ticket originally is...
