### ISSUE TITLE
If connection string name is changed from MembershipReboot, cannot connect to database.  

### ISSUE THREAD

**Issue by jdulay** [brockallen/BrockAllen.MembershipReboot#415]
The DefaultMembershipRebootDatabase(string nameOrConnectionString) is not using the correct base constructor.  It should be base(nameOrConnectionString, null).

namespace BrockAllen.MembershipReboot.Ef
{
    public class DefaultMembershipRebootDatabase : MembershipRebootDbContext<RelationalUserAccount>
    {
        public DefaultMembershipRebootDatabase()
            : base()
        {
        }

```
    public DefaultMembershipRebootDatabase(string nameOrConnectionString)
        : base()
    {
    }

    public DefaultMembershipRebootDatabase(string nameOrConnectionString, string schemaName)
        : base(nameOrConnectionString, schemaName)
    {
    }
}
```

}

**Comment by StateBarofArizona** [comment]
What is the correct update for IdentityReposity.cs  when using with IdentityServer2?  The arguments can no longer be empty.
