### ISSUE TITLE
MySql Exception on db creation

### ISSUE THREAD

**Issue by esko22** [brockallen/BrockAllen.MembershipReboot#454]
Hi Brock,

About a month ago I posted an issue I was having trying to get MR to work with MySql. I was finally able to get some time to look into it today.

There are two minor issues....

First,  the SetSqlGenerator needs to be set in the Migration Configuration

<code>
            SetSqlGenerator("MySql.Data.MySqlClient", new MySql.Data.Entity.MySqlMigrationSqlGenerator());
</code>

Second, once I was able to get around this I ran into an issue generating the migrationHistory table based on single column index sizes in MySql...
http://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html  

I looked around and found the following.... 
http://www.asp.net/identity/overview/getting-started/aspnet-identity-using-mysql-storage-with-an-entityframework-mysql-provider

All said and done... I was able to get it working with a Migration Configuration class that looks like this...

<pre>
public sealed class Configuration : DbMigrationsConfiguration<DefaultMembershipRebootDatabase>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            SetSqlGenerator("MySql.Data.MySqlClient", new MySqlMigrationSqlGenerator());
            SetHistoryContextFactory("MySql.Data.MySqlClient", (conn, schema) => new MySqlHistoryContext(conn, schema));
        }

        protected override void Seed(DefaultMembershipRebootDatabase context)
        {           
        }
    }

    public class MySqlHistoryContext : HistoryContext
    {
        public MySqlHistoryContext(
          DbConnection existingConnection,
          string defaultSchema)
            : base(existingConnection, defaultSchema)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<HistoryRow>().Property(h => h.MigrationId).HasMaxLength(100).IsRequired();
            modelBuilder.Entity<HistoryRow>().Property(h => h.ContextKey).HasMaxLength(200).IsRequired();
        }
    }
</pre>

Please let me know if you'd like me to try anything else...

Thanks!

**Comment by brockallen** [comment]
Following up on this  -- it's been a while since I've looked into migrations. Can you use a derived migration class? Does the command line let you indicate the class name?

**Comment by esko22** [comment]
Sorry for the delayed response. Yes, my work around was to use a derived class so I could specify the MigrationSqlGenerator. 

Initially I was just hoping to get an out of box solution since I didn't change the schema at all.  I wasn't sure if it would make sense to extend the MR migration config in the case you needed to put something  explicit in there but since it is sealed you can't.

I don't believe the command line allows you to specify the migration configuration class, only the specific migration to ran. With as wonky as migrations get, I think your call to put it on the owner makes complete sense as long as nothing custom winds up in your MR migration config class.

**Comment by brockallen** [comment]
Ok, thx,
