### ISSUE TITLE
Authenticating Web API

### ISSUE THREAD

**Issue by jahnavisdba** [brockallen/BrockAllen.MembershipReboot#465]
Hi  Brock,

We have a website that uses membership framework for authentication.
Now we are trying to implement a MVC web API. We would like to use the same membership authentication for the API too. Client apps should be able to pass credentials to the API end point and get authenticated.
Can you please guide on how this could be implemented?

Thanks.

**Comment by rpundlik** [comment]
@jahnavisdba How can I contact you regarding this ? I just wanted to ask finally how you have implemented everything ?
