### ISSUE TITLE
Please add an interface to UserAccount and utilise in IUserAccountQuery sort/filter

### ISSUE THREAD

**Issue by johnbirdau** [brockallen/BrockAllen.MembershipReboot#467]
Hi

We use a custom EF Model for storing user and related table rows in our database due to local DB schema policies. 
Hence whilst we can utilise UserAccount and RelationalUserAccount (with some imposing workarounds to get around the "protected internal set" properties) in derived classes, we cannot use them for the EF models as is done by MembershipReboot.Ef solution.

Hence we map our EF model classes (after DB retrieval) into subclasses of RelationUserAccount and other Relational\* classes.

The recently added query interface
IUserAccountQuery<TAccount> where TAccount : UserAccount
is proving to be quite problematic, as it requires (for efficient operation) a concrete subclass of UserAccount during the LINQ to Entities query.

This request is to add (for example) an interface to be added to UserAccount class with only those properties on it for filtering/sorting, and using that interface in the query interface.
For example
IUserAccountQuery<TAccount> where TAccount : IUserAccount

The intention is to allow efficient queries without pushing the heavy UserAccount abstract class all the way down into our EF Model.

Thanks for your consideration.

**Comment by brockallen** [comment]
Any updates?

**Comment by dealproc** [comment]
curious about this myself.  customer is running into this need right now (puke) and need to support.  other option is to build a custom projection object and go to town, i believe.

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
