### ISSUE TITLE
ChangePassword validation sequence

### ISSUE THREAD

**Issue by johnbirdau** [brockallen/BrockAllen.MembershipReboot#473]
Brock, 

the current implementation of UserAccountService.ChangePassword includes the following (abbreviated) code sequence...

            var account = this.GetByID(accountID);
            ValidatePassword(account, newPassword);
            if (!VerifyPassword(account, oldPassword))
            {
                throw new ValidationException(GetValidationMessage(MembershipRebootConstants.ValidationMessages.InvalidOldPassword));
            }
            SetPassword(account, newPassword);

The issue with this is that I can POST many change password HTTP requests with garbage in the old password field and guesses in the new password field. If I manage to correctly guess the current password via the new password field, I get the response "The new password must be different than the old password."

It feels like a security hole since it bypasses CheckHasTooManyRecentPasswordFailures check and RecordInvalidLoginAttempt audit log in VerifyPassword() method

It potentially could be easily closed by changing the above code sequence to...

            var account = this.GetByID(accountID);
            if (!VerifyPassword(account, oldPassword))
            {
                throw new ValidationException(GetValidationMessage(MembershipRebootConstants.ValidationMessages.InvalidOldPassword));
            }
            ValidatePassword(account, newPassword);
            SetPassword(account, newPassword);

Regards
John

**Comment by brockallen** [comment]
Ok, so I finally had time to look into this and I now see and understand the details. So really tehc hange is just an ordering change -- correct? I think that's fine. I'll make this change on dev now. Again, nice find.

**Comment by johnbirdau** [comment]
Correct. Just an ordering change. 

John

**Comment by brockallen** [comment]
Ok, done. Thx.
