### ISSUE TITLE
UserAccountService: Update, ChangeUsername, ChangeEmailRequest, GetByID not getting all the updates

### ISSUE THREAD

**Issue by chrisaswain** [brockallen/BrockAllen.MembershipReboot#474]
I have a Web Api Put action that is using the UserAccountService to update my CustomUserAccount by making a call to Update, then ChangeUsername, then ChangeEmailRequest.  Finally, I make a call to GetByID to get an updated version of my CustomUserAccount.  However, for some reason, the GetByID method is not pulling the CustomUserAccount with the change I made to the email.  But, if I run the Put action a second time, I will see the updated email.  The GetByID method is acting like the email has not yet been updated when I call it.  Is there a trick to getting this kind of full update of my CustomUserAccount to work?

**Comment by brockallen** [comment]
My first question is around all of the Task code you have. From what I can tell, none of it is necessary or useful. MR does not have an async API, so I think this is a lot of overhead/confusion for no benefit. It also make the code hard for me to follow :S

**Comment by chrisaswain** [comment]
Sorry.  The async code was my attempt to force the processes to run in a particular order and it originally had some sleep code in there to give the database time to update before trying the next method.  

Here is the code now:

            CustomUserAccount customUserAccount = null;

            customUserAccount = _userAccountService.GetByID(id);
            customUserAccount.UpdateWith(updateAccountRepresentation); //Maps changes to CustomUserAccount from the updateAccountRepresentation object.

            _userAccountService.Update(customUserAccount);

            if (updateAccountRepresentation.Username != customUserAccount.Username)
            {
                _userAccountService.ChangeUsername(id, updateAccountRepresentation.Username);
            }
            if (updateAccountRepresentation.Email != customUserAccount.Email)
            {
                _userAccountService.ChangeEmailRequest(id, updateAccountRepresentation.Email);
            }
            customUserAccount = _userAccountService.GetByID(id);

            return Ok(customUserAccount.ToAccountRepresentation());

**Comment by brockallen** [comment]
Right, so that looks like it should be ok. Each time you call into the user account service to perform an operation it does query the repository and if you're using EF it will pull from any in-memory cached instance. But, having said that, the in-mem cached instance should get updated when SaveChanges is called internally.

Are you able to debug into it anymore (into the MR code) and perhaps do some more investigation?

**Comment by chrisaswain** [comment]
I think the root of the problem somehow was coming from the fact that I was using both MR.WebHost and MR.Owin assemblies.  Removing the use of MR.WebHost seems to have cleared things up.

**Comment by brockallen** [comment]
Ah, good news then.
