### ISSUE TITLE
Web Api and Owin

### ISSUE THREAD

**Issue by chrisaswain** [brockallen/BrockAllen.MembershipReboot#476]
I'm using MR in an Owin based Web Api project just to handle my user management.  I have my own Authorization server middleware and have it setup to implement OAuth2 Refresh Token process flow.  

I'm getting the following error in my Post action when trying to create a new CustomUserAccount:

System.ArgumentNullException occurred
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: ctx
  Source=BrockAllen.MembershipReboot.WebHost
  ParamName=ctx
  StackTrace:
       at BrockAllen.MembershipReboot.WebHost.HttpContextExtensions.GetApplicationUrl(HttpContext ctx) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot.WebHost\HttpContextExtensions.cs:line 17
  InnerException: 

Have you seen this before?

Here is my configuration from my startup.cs:

            Database.SetInitializer(CustomMembershipDatabase.GetDatabaseInitializer());

            var resolver = new UnityDependencyResolver(UnityConfig.GetConfiguredContainer());

            ConfigureAuth(app);

            var config = new HttpConfiguration();
            config.DependencyResolver = resolver;
            app.UseMembershipReboot();
            WebApiConfig.Register(config);
            app.UseWebApi(config);

            AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier;
            MvcFilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            WebApiFilterConfig.RegisterHttpFilters(GlobalConfiguration.Configuration.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

And the code to create the new user account in my post action looks like:

var customUserAccount = _userAccountService.CreateAccount(
                SecuritySettings.Instance.DefaultTenant,
                createAccountRepresentation.Username,
                createAccountRepresentation.Password,
                createAccountRepresentation.Email,
                Guid.NewGuid(),
                DateTime.Now.ToUniversalTime());

The _userAccountService field is populated in the constructor of my ApiController via the Unity IoC constructor injection.  

I have a unit test project that uses the same UserAccountService, but it is "newed" up manually just before using it.  In that project, the call works.

**Comment by brockallen** [comment]
Are you mixing the Owin and System.Web hosting models with MR?

**Comment by chrisaswain** [comment]
I think I might be.  I started off with the project being just a plain vanilla Web Api template with the default "Help" area and all.  Then I added the startup.cs and tried to move everything over to it and stop using the Global.asax. 

I plan to deploy it to IIS on Azure at a later date, so I don't want to do anything that will prevent that.  

What might I need to do to strictly use the Owin model and stop using the System.Web model?

**Comment by brockallen** [comment]
You should only be using one of either the MR.Owin or MR.WebHost library (but not both).

**Comment by chrisaswain** [comment]
Okay, I just removed the reference to MR.WebHost and there are some things broken.  

I have the following code that is not recognized now:

            var appinfo = new AspNetApplicationInformation("Test", "Test Email Signature",
                "UserAccount/Login",
                "UserAccount/ChangeEmail/Confirm/",
                "UserAccount/Register/Cancel/",
                "UserAccount/PasswordReset/Confirm/");
            var formatter = new CustomEmailMessageFormatter(appinfo);

            config.AddEventHandler(new EmailAccountEventsHandler<CustomUserAccount>(formatter, delivery));

And in my Unity regristration:

container.RegisterType<AuthenticationService<CustomUserAccount>, SamAuthenticationService<CustomUserAccount>>();

It doesn't recognize "AspNetApplicationInformation" and "SamAuthenticationService".  Do I even want these anymore?  If so, what is the MR.Owin way of doing it?

**Comment by chrisaswain** [comment]
Here is my full configuration for MR:

public class MembershipRebootConfiguration
    {
        public static MembershipRebootConfiguration<CustomUserAccount> Create()
        {
            var settings = SecuritySettings.Instance;
            settings.MultiTenant = false;
            settings.DefaultTenant = ConfigurationManager.AppSettings["defaultMembershipTenant"];
            settings.RequireAccountVerification = false;  //TODO:Set this to true before pushing to production

            var config = new MembershipRebootConfiguration<CustomUserAccount>(settings);
            config.AddEventHandler(new DebuggerEventHandler<CustomUserAccount>());

            //config.RegisterPasswordValidator(new CustomPasswordValidator());
            config.ConfigurePasswordComplexity(6, 4);

            config.AddCommandHandler(new CustomClaimsMapper());

            var delivery = new SmtpMessageDelivery();

            var appinfo = new AspNetApplicationInformation("Test", "Test Email Signature",
                "UserAccount/Login",
                "UserAccount/ChangeEmail/Confirm/",
                "UserAccount/Register/Cancel/",
                "UserAccount/PasswordReset/Confirm/");
            var formatter = new CustomEmailMessageFormatter(appinfo);

            config.AddEventHandler(new EmailAccountEventsHandler<CustomUserAccount>(formatter, delivery));
            config.AddEventHandler(new AuthenticationAuditEventHandler());
            config.AddEventHandler(new NotifyAccountOwnerWhenTooManyFailedLoginAttempts());

            config.AddValidationHandler(new PasswordChanging());
            config.AddEventHandler(new PasswordChanged());
            config.AddCommandHandler(new CustomValidationMessages());

            return config;
        }
    }

**Comment by brockallen** [comment]
I'd suggest looking in the SingleTenantOwinSystemWeb sample to model what you need -- it's an example of using MR with OWIN/Katana in IIS. 

The main change is that you'd use `OwinApplicationInformation` instead of `AspNetApplicationInformation`.

**Comment by chrisaswain** [comment]
That did it!  Thanks!
