### ISSUE TITLE
How to retrieve users with claims

### ISSUE THREAD

**Issue by theythinkimmexican** [brockallen/BrockAllen.MembershipReboot#478]
Is there an example anywhere that shows how to retrieve a list of all user accounts along with their claims? Using the IUserAccountQuery interface returns a limited number of properties of the account and does not include claims.

**Comment by brockallen** [comment]
The idea is that the IUserAccountQuery is for high level queries so then an individual account can be loaded. 

Recently I added IQueryable<T> Users property on the UserAccountService -- I don't know if that's in the latest on NuGet or not...

**Comment by theythinkimmexican** [comment]
Thanks for the quick response. There's no Users property on the UserAccountService in my solution which is using the NuGet package so I guess it's not been updated. I'll get the source and use that instead. 

Cheers!
