### ISSUE TITLE
Register, Then Attempted Login Before Email Verification Invalidates Email Verification Link

### ISSUE THREAD

**Issue by ascottwhite** [brockallen/BrockAllen.MembershipReboot#482]
We seem to be having the following issue:

1. A User registers (verification required).

2. A verification email is sent.

3. The user doesn't click the link on the verification email but just attempts to login, which fails because they have not verified.

4. Then, when they click on the link in the verification email, they get an "Invalid Key" error. It's as though the attempted login has invalidated the verification key in the link in the email.

At that point they are stuck. Unable to login because they have not verified and also unable to verify because the link is now invalid.

Are we doing something wrong? Is this a common issue/scenario?

Please advise.

Thanks.

**Comment by brockallen** [comment]
If they request a password reset and their email account has never been verified then a new verification email will be sent (as if they had just signed up). 

The email verification token expiration timeout can be changed via .config or in the MR config object.

**Comment by ascottwhite** [comment]
Thanks for your quick response.

It doesn't seem to be a token expiration issue. Sometimes less than a minute or two has passed. It seems as though the login attempt itself is invalidating the token/key sent in the verification email. Is that possible?

**Comment by ascottwhite** [comment]
One other question: Is there a way to resend the verification email without requiring that they change their password?

Thanks again.

**Comment by brockallen** [comment]
Ok, not sure I follow the sequence. I'll see if I can find time to repro what you're saying. Any interesting configuration you have that might affect this or be related?

**Comment by ascottwhite** [comment]
Nothing fancy.

<membershipReboot requireAccountVerification="true" emailIsUsername="true" multiTenant="false" passwordHashingIterationCount="0" accountLockoutDuration="00:01:00" passwordResetFrequency="0"/>

Thanks.

**Comment by brockallen** [comment]
To re-trigger the verification email for new accounts just call `ResetPassword`

**Comment by ascottwhite** [comment]
Will they have to actually change their password? Thanks again.

**Comment by brockallen** [comment]
No. If the account has never confirmed the email we don't trust the email, so we don't allow password resets until the email has been confirmed.

**Comment by ascottwhite** [comment]
Got it. Thanks again.

**Comment by StateBarofArizona** [comment]
Brock, we are seeing a similar situation.  Either the email never reaches them or they just don't bother to check for the email.  They try to login right away and then they brick their account.  How long can you realistically extend the expiration of the verification link?  Is it safe to let them say verify several days or a week later?

**Comment by brockallen** [comment]
Sure, make it a month if you want. The idea is that normally when a user is sitting there setting up an account, they're actively waiting to get the link so they can login.

**Comment by brockallen** [comment]
Oh and I've not had the time to try to repo this yet. I've been busy on IdSvr's release (due next week). Once that's done, I'll have some breathing room to come back and follow up on these open issues.

**Comment by StateBarofArizona** [comment]
Actually IdSvr is something I need to take another look at, before building my own solution.  Any teases or can you be sure to let us know when it’s official?

Connie DeCinko, Programmer Analyst
T: 602.340.7290  F: 602.416.7490

**Comment by brockallen** [comment]
We plan on shipping next week: https://github.com/thinktecture/Thinktecture.IdentityServer.v3/milestones

**Comment by StateBarofArizona** [comment]
I added VerificationKeyLifetime="02:00:00" to the <membershipReboot section of our web.config but it's causing the server to throw a 500 error.  Is this the correct format?  I see that it's supposed to be a timespan so I formatted it like accountLockoutDuration.

	<membershipReboot 
			requireAccountVerification="true" 
			emailIsUsername="true" 
			multiTenant="false"
			defaultTenant="AZBar"
			allowAccountDeletion="false" 
			passwordHashingIterationCount="3" 
			accountLockoutFailedLoginAttempts="5"
			accountLockoutDuration="00:05:00" 
			passwordResetFrequency="0"
			VerificationKeyLifetime="02:00:00"/>

**Comment by brockallen** [comment]
What version are you on? The latest on NuGet has it in there.

**Comment by StateBarofArizona** [comment]
Using 7.2.  Looks like you exposed this feature just after that version.

**Comment by StateBarofArizona** [comment]
Brock, where is the change log? I need to see what is going to break when I go from 7.2 to 8.1.  Thanks.

**Comment by brockallen** [comment]
You know what -- I've not been keeping up on that (mainly because there have not been many changes). The main place is the commit history. But since you're on 7.x and it's now up to 8.x that means there is at least one breaking change. Again -- look at the checkin history. I know that's not a very satisfactory answer, so my apologies.

https://github.com/brockallen/BrockAllen.MembershipReboot/commits/master
