### ISSUE TITLE
Multiple Web Servers and EF Caching

### ISSUE THREAD

**Issue by jamyryals** [brockallen/BrockAllen.MembershipReboot#483]
Scenario we are seeing -
1. A user registers and receives an email to verify their account.
2. User tries to take an action on Webserver1, but fails because they need to verify account.
2. The user clicks the link and verifies their account successfully with Webserver2. 
3. Webserver2 thinks the user is verified.
4. Webserver1 thinks the user is **NOT** verified. 
5. The database says the user is verified. 

We are using the DefaultUserAccountRepository, and we suspect it's EF caching causing the problem. Does EF caching seem like a likely culprit to you? 

If so, is it possible to use the DefaultUserAccountRepository without EF caching or do we need to reimplement the IUserAccountRepository?
If not, any thoughts?

Thanks for the time Brock.

**Comment by brockallen** [comment]
You should be creating a new instance of the UserAccountService, and the UserAccounrRepository, and thus the DbContext on each request. These classes aren't thread safe. I suspect this is the issue.

**Comment by jamyryals** [comment]
It seems you've hit the nail on the head. We are keeping an instance of the UserAccountService and UserAccountRepository in an IOC container. I'll update here when we've made the modifications to confirm. Thanks!

**Comment by jamyryals** [comment]
I forgot to reply after confirming fix. That was exactly it Brock, thanks!
