### ISSUE TITLE
I can't even get the samples to work

### ISSUE THREAD

**Issue by rmatrix** [brockallen/BrockAllen.MembershipReboot#484]
Hi Brock,

I've tried everything to get even one sample to work. I'm running under IISExpress and set "access" overrideModeDefault to "Allow" as defined in the "configuring_client_certs_readme.txt" file. I keep getting page not found. 

Anyhelp would be greatly appreciated.

R

**Comment by brockallen** [comment]
Are you asking about IdentityServer3? I think you're posting to the wrong repository.

**Comment by rmatrix** [comment]
No it was with the MembershipReboot samples in this git repository. I figured it out. I installed SQL Express as a default instance and the Config files in the sample were pointing to (LocalDb)11.0\....  I  removed the 11.0 and now all samples work fine :)

Thanks for getting back to me and sorry for my misconfiguration.

R
