### ISSUE TITLE
Can't verify account on custom user example

### ISSUE THREAD

**Issue by sheam** [brockallen/BrockAllen.MembershipReboot#485]
I have the CustomizationSample working fine. Already love it more than messing with IdentityFramework 2.0.

But in my own app, I keep this this error when trying to confirm the email:

ID7027: Could not load the identity configuration because no <system.identityModel> configuration section was found.

Here is the call stack:
![image](https://cloud.githubusercontent.com/assets/1779211/5950667/da0d9924-a722-11e4-8759-f145b806fff7.png)

It appears that Ninject doesn't know how to creat eh SamAuth service? But my NinjectWebCommon is nearly identitcal to the example.

What am I missing here?
A minimal solution is here: https://onedrive.live.com/redir?resid=5B7EFAE13184E622!3665&authkey=!AGrZoUmgO8Om0UQ&ithint=file%2czip

Or if you woud rather: https://bitbucket.org/sheam/mr-test-app/src

The issue could be my ignorance of Ninject, as I have always used SimpleInjector. But I am pretty sure I have things set up the same as your sample.

Thanks,

~Shea M.

**Comment by brockallen** [comment]
Do you have the SAM configured in `<modules>` in web.config? Also, do you want to use OWIN or SYstemWeb?

**Comment by sheam** [comment]
Brock,

Indeed my web.config was badly out of shape. This commit fixed everything:
https://bitbucket.org/sheam/mr-test-app/commits/94e174abae643dcaea82cc77c7c446644f0d0810
Hopefully it helps others.

OWIN would be nice, but likely not needed for me at this point... is it something I should decide now? Or is easy to change my mind later?

Thanks again.

**Comment by brockallen** [comment]
Well, it affects how you manage cookies. OWIN does the authentication cookie differently than if you're doing SystemWeb hosting. OWIN is newer and thus the one that will typically be used moving forward.

**Comment by sheam** [comment]
Thanks for the advice. I will look into OWIN more. Feel free to close this.

**Comment by brockallen** [comment]
Here's a video on OWIN:
http://vimeo.com/97329189

Here's a post on the cookie middleware:
http://brockallen.com/2013/10/24/a-primer-on-owin-cookie-authentication-middleware-for-the-asp-net-developer/
