### ISSUE TITLE
When password has expires Authenticate still returns true

### ISSUE THREAD

**Issue by christianacca** [brockallen/BrockAllen.MembershipReboot#487]
Hi Brok,

Doing a spot of digging into the code. Just found that when a users password has expired, the `Authenticate` method still returns true. 

Looking at the code in `LoginController.Index` this is by design.

Truth be told, *I don't like that design!* It seems an unsafe default - just saying. It took me by surprise as I had in my head that Authenticate was another name for CanLogin...

C

**Comment by brockallen** [comment]
Well, how could you validate the credentials to allow them to change the password if it's expired? This is something that is up to the hosting app to check after authentication -- as the samples show.

**Comment by christianacca** [comment]
Agreed. It just took me by surprise.

I think I would have preferred the Authenticate method to have returned an AuthenticateFailureType enum

That way for the simple case where consumer code just wants to know if the user is allowed to login:

````
if (userAccountService.AuthenticateWithEmail(...) == AuthenticateFailureType.None) {
  // allow login
} else {
 // disallow login
}
````

Or for the more sophisticated consumer:
````
switch (userAccountService.AuthenticateWithEmail(...).FailureType)
{
    case AuthenticateFailureType.None:
        // handle login success
    case AuthenticateFailureType.InvalidCredentials:
        // handle failure
    case AuthenticateFailureType.PasswordExpired:
        // handle failure
    case AuthenticateFailureType.TwoFactorAuthCodeRequired:
        // handle failure
    case AuthenticateFailureType.TwoFactorAuthCertRequired:
        // handle failure
    case AuthenticateFailureType.PasswordResetRequired:
        // handle failure
}

**Comment by brockallen** [comment]
Sure -- but this grew over time into that list. Thus the extension methods on the UserAccount. *shrug*

**Comment by christianacca** [comment]
Seems a shame not to change things so that it could return an enum.

I think it would provide a much simpler api to the consumer - a single query method to call rather than have to fish around in all the properties and extension methods of the UserAccount.

C

**Comment by brockallen** [comment]
I'd be ok making that change -- in a vNext (since it's a breaking change). This then gets into the question of ASP.NET 5 and their new (new new) Identity library (since v3 isn't compat with v2 -- so much for them *finally* getting it right) -- I'm wondering if MR offers anything beyond what's in AspNet5.

**Comment by christianacca** [comment]
Also by returning an enum, the api would afford to take on extra reasons for not allowing login without all consumers necessarily having to be adjusted to check for this new reason.

**Comment by christianacca** [comment]
Ah so I didn't know about this new new Identity library!

**Comment by christianacca** [comment]
I do prefer the most of the design choices in MR over what I have seen in Identity 2.0

**Comment by ccrowhurstram** [comment]
So Brock are you happy for an API change as mentioned: https://github.com/brockallen/BrockAllen.MembershipReboot/issues/487#issuecomment-72376170

**Comment by brockallen** [comment]
Perhaps put this on a branch to review, chat about it, etc.

**Comment by ccrowhurstram** [comment]
OK makes sense

**Comment by brockallen** [comment]
Also, feel free to ping me on skype.

**Comment by ccrowhurstram** [comment]
Thanks Brock

**Comment by brockallen** [comment]
Fixed via PR.
