### ISSUE TITLE
Read/Write from a custom table

### ISSUE THREAD

**Issue by sandeepgaikwad** [brockallen/BrockAllen.MembershipReboot#489]
Hi Brock,
I am using MembershipReboot for user management
Things are working pretty well so far.
But I have a requirement to read and write from a custom table. I saw that you already have a custom table "SomeOtherEntity" in one of your examples, but I can't find a way to read and write to this table.
Is there an example available or can you help me with one

Thanks

**Comment by brockallen** [comment]
That's something really outside the realm of MembershipReboot. Just use EF or whatever DB library you want.
