### ISSUE TITLE
DefaultUserAccountRepository does not contain a constructor that takes 0 arguments

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#490]
I am upgrading my IdentityServer2 with MembershipReboot 7.1 to MembershipReboot 8.  I have everything compiling except for one error.
In MembershipRebootUserRepository IdentityRepository.cs I get this error:

  BrockAllen.MembershipReboot.Ef.DefaultUserAccountRepository does not contain a constructor that takes 0 arguments.  

When I F12 into the definition, I see the method takes a class that has none as an argument.

**Comment by brockallen** [comment]
Yes, this was one change. A `DefaultMembershipRebootDatabase` is now required as a ctor param. So you'd just create one of those (either with or without its own ctor param to indicate the connection string).

**Comment by StateBarofArizona** [comment]
OK, got it to build.  Now let's see if it will run!

**Comment by StateBarofArizona** [comment]
Problem solved.

DefaultMembershipRebootDatabase db = new DefaultMembershipRebootDatabase();
...
var uarepo = new DefaultUserAccountRepository(db);
