### ISSUE TITLE
Allow email to be non-unique

### ISSUE THREAD

**Issue by brockallen** [brockallen/BrockAllen.MembershipReboot#491]
This would require a non-email based approach for users to reset passwords.

**Comment by StateBarofArizona** [comment]
Then how do you verify/validate a user's identity if their email is not unique?

**Comment by brockallen** [comment]
That would be up to the app. That means the email-only based way to reset password would not work.

**Comment by tjrobinson** [comment]
We have an awkward scenario where users are soft-deleted - CloseAccount() rather than DeleteAccount() - and then re-created at a later date with a different username but the same email address. In these cases it would be possible to allow the email to be non-unique within the set of all currently "unclosed" users. Obviously this would mean you wouldn't be able to re-open the original user account.

**Comment by brockallen** [comment]
Yep, that gets complex.

**Comment by brockallen** [comment]
Ok, this has now been added to dev. 

@tjrobinson if you'd like to look at how to change things to support the post-closed scenario, and propose a change or PR, let me know.

**Comment by ccrowhurstram** [comment]
Not sure this is the only thread discussing uniqueness of email address...

Anyway, I've hit problems with soft deleted records failing unique constraints - it's a general problem and a pain not limited to user accounts.

One general approach I've taken is to ensure that *linq queries exclude soft deleted accounts by default*. To then offer a consumer a way to "opt in" to returning set's that include soft deleted records on a query by query basis.

I've found in practice that most code should not receive the soft deleted records and by making this the default, such problems like duplicates don't bite.

For those use cases that really need to see soft deleted, that code only asks for them.

So the above sounds a bit vague and lacking implementation detail. The reason for vagueness is that I have never been completely satisfied when using Entity Framework in making the implementation transparent to the majority of the code.

C
