### ISSUE TITLE
RequestAccountVerification sends incorrectly labeled email

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#492]
When a user creates a new account, then tries to login with this new account before the email address has been verified, they get denied access.

First, what would be the harm of automatically resending the verification email at the moment?

So, the user is in limbo.  They click to reset their password because perhaps the password on file is not what they think it is.  Why not provide a button to resend the verification?  Anyway, MR sees they have not verified their address and sends an email with a new verify link.  Problem:  the email used is the one that says "Email Change Requested."  Huh?  However the link in the email is correct.  It takes them to the verification page and asks for their password.  Wait, how can I enter my password when I just said I don't remember it, please send it to me?

Is this something I have to fix or something that should be fixed in the MR core?

**Comment by brockallen** [comment]
You should provide a link to resend the verification -- I think one of the samples has that. IIRC, if the user tried to reset the password but they've never logged in, MR re-sends the original verification email, rather than sending a password reset email (IOW, it raises 2 diff events based upon the state of the user account).

**Comment by StateBarofArizona** [comment]
Actually, if the user tries to reset a password and hasn't logged in, they get an Email Change email.
Take a look at public virtual void RequestAccountVerification(Guid accountID) in UserAccountService.cs, the last part seems wrong.

            Tracing.Verbose("[UserAccountService.RequestAccountVerification] creating a new verification key");
            var key = SetVerificationKey(account, VerificationKeyPurpose.ChangeEmail, state: account.Email);
            this.AddEvent(new EmailChangeRequestedEvent<TAccount> { Account = account, NewEmail = account.Email, VerificationKey = key });

Why would you send an EmailChangeRequestedEvent?

**Comment by StateBarofArizona** [comment]
Actually, I see what you are doing.  You use the same "Validate your Email Address" email for a new account and for anyone changing the email address on their account.  I just need to make my custom verbiage more generic.

**Comment by StateBarofArizona** [comment]
Brock, do you happen to recall which sample has the resend verification link?  I've not been able to find it.

**Comment by brockallen** [comment]
Do you mean the `RequestAccountVerification` API?

**Comment by StateBarofArizona** [comment]
I figured it out.  First, pass the email to userAccountService.GetByEmail to get the account.  From account pass the ID to userAccountService.RequestAccountVerification.  Now I get the correct responses for existing, non-existing and already verified accounts.  Works like a charm.  Next would be adding a layer of protection from abuse.  I don't want a bot sitting on that page passing email addresses over and over looking for valid ones.

**Comment by brockallen** [comment]
Ok, glad you found it. As for the bot... yea... perhaps an exercise for the reader? :)
