### ISSUE TITLE
External Account (i.e. Google) User Registration and Login Flow

### ISSUE THREAD

**Issue by chrisaswain** [brockallen/BrockAllen.MembershipReboot#494]
I have an Owin Web Api 2 project where I am using MembershipReboot EF as my User Management library.  I have an Account api controller that currently lets a user register via a POST as well as update and get their user info via the usual REST HTTP verbs.  I've also implemented the typical /api/token endpoint to provide OAuth2 authentication that gives the app client a JWT bearer token to use to access the api.  If I have an AngularJS web app that will use the Web Api, and I want to allow my users to register and login using either an external account or by creating a new username/password.  What should the process flows be?  The flow for creating a regular user account is straight forward.  What I'm not so clear on is the flow for creating a new account that is associated/linked with a Google or Facebook account.  Do I still need to make the user create a username/password or is there an api in MR that will let me create a new account from the info returned by letting the user use their Google or Facebook credentials?

**Comment by brockallen** [comment]
You can create an account in MR without a password (for this external-provider only scenario).

**Comment by chrisaswain** [comment]
Two questions come to mind with the no password suggestion:

1. How would I create a user with no password if I have MR configured to require a strong password?
2. If there is not a password for a user, but that user has a valid username, wouldn't that be a security hole that could allow someone to use that username with a blank password to authenticate?

**Comment by brockallen** [comment]
1) Password can be null -- MR allows for this, but then of course password authentication is not allowed
2) See (1)

**Comment by chrisaswain** [comment]
Regarding queston #1 I suppose I could generate a random strong password.  I could also store an extra bit of metadata in the UserAccounts table indicating that the account is external only.  Then, if they wanted to switch over to using just a local login, that process would be little more than the password change/reset process.  

Once the user is created using just their linked account credentials, I suppose the login process via the "/token" endpoint should include a way for an app to pass the external access token provided by Google to the client app rather than the standard username/password/client_id/grant_type combo in order to get a valid JWT for my web api.  Does that sound right?  If so, is there a standard OAuth flow that I should follow for requesting a local access token using an external access token?

**Comment by brockallen** [comment]
I guess I don't see the need to generate a strong password -- MR allows for null passwords and knows to not allow users to try to user username/password to login (only external logins). What am I missing?

**Comment by chrisaswain** [comment]
So even though in my MembershipRebootConfiguration I have `config.ConfigurePasswordComplexity(6, 4);`, I should be able to call '_userAccountService.CreateAccount("someUserName", null, ...)` and it won't give me a validation exception?

**Comment by brockallen** [comment]
Right -- the complexity is only enforced if a non-null password is provided. Are you seeing a different behavior?

**Comment by chrisaswain** [comment]
Awesome!  No, haven't tried it yet.  Just working through the logic and process flow.  Not sure if you hear this enough, but you've done a great job with MR!

I know this is off topic, but you wouldn't happen to know if there is an OAuth 2 flow (maybe a special grant_type) that would support a client passing the Google or Facebook access_token to my auth provider "/token"?  All of the example I find out on the web have a separate Web Api action like "api/Account/ObtainLocalAccessToken(string provider, string externalAccessToken)" and that feels like it is breaking the OAuth flow.  It seems like there should be a grant_type=external and external_token=xxxxx...

**Comment by brockallen** [comment]
That's called a custom grant type. You'd need to implement the "assertion flow" of OAuth2.

**Comment by chrisaswain** [comment]
Excellent!  I was reading through the OAuth 2 specs, but you just saved me some time!  Thanks!

**Comment by brockallen** [comment]
np
