### ISSUE TITLE
MembershipReboot for multi site

### ISSUE THREAD

**Issue by dandresini** [brockallen/BrockAllen.MembershipReboot#495]
hi,
I want to use MembershipReboot with Identity Server v3 to implement SSO.
Would that users register once and use their profile to access other six sites. In addition to the common information (name, email billing address), I have to record other information broken down by the sites that I am executing the login request (example 1 site asks the number of a discount card, while the second site requires the formation of the household ). I can organize this information within the MembershipReboot, or advisable insert them within the various DB? If you do I use?

**Comment by brockallen** [comment]
Identity data would be shared across many apps, whereas app specific data should stay in the application database.
