### ISSUE TITLE
Closed Account prevents creation of new account with same name/email

### ISSUE THREAD

**Issue by sheam** [brockallen/BrockAllen.MembershipReboot#497]
Hello,

I like the soft-deleting of users, as it simplifies what to do with records that the user owns. However it does prevent any user from ever having that username or email in the future. I tried renaming the email to 'retired_' + oldUsername, and then setting the email to null, but that results in an email being sent to the user notifiying them of the new username (weird considering their account is closed), and then I get an exception when I try to set email null.

Any suggestions for this situation?

~S

**Comment by brockallen** [comment]
For the scenario where you don't want emails sent, use a user account service whose MR configuration don't have an email handler registered.

**Comment by sheam** [comment]
And then with the email handler null, I could just SetConfirmedEmail(account.ID, "retired_" + account.Email), which would allow that user to sign up with that email again?

**Comment by brockallen** [comment]
Sounds like that'd work.

**Comment by sheam** [comment]
Calling CloseAccount(uid) does not work, as the source for that f'n does not call Update on the account. The CloseAccount(userObject) is inaccessible.

Should I be using DeleteAccount(uid) with AllowAccountDeletion = false?

**Comment by brockallen** [comment]
Ah, that looks like a bug then.

**Comment by brockallen** [comment]
Fixed and pushed to NuGet. Thx.

**Comment by sheam** [comment]
Thank you.
