### ISSUE TITLE
Any breaking changes going from MR 7.1 to MR 8.2

### ISSUE THREAD

**Issue by JellyMaster** [brockallen/BrockAllen.MembershipReboot#498]
Hi Brock. 

I have been using MR for a while and wondering if there are any breaking changes going from 7.1 to 8.2 

I have an established database with a a few hundred users and obviously don't want to toast the database by accident. Do the change/updates affect more the c# code rather than the database schema? 

Thanks in advance.

**Comment by brockallen** [comment]
Well, we did a version bump (7 to 8) so something is a breaking change. I admit I've not done a good job of keeping on top of the releases to list these things though. IIRC, it was a minor API change (but breaking nonetheless).

**Comment by JellyMaster** [comment]
Ok. Thanks Brock. I will probably test it out and see what has affected my projects. I am more concerned about the database than I am the API's. I will run a schema compare and see if there is anything that has fundamentally changed (hopefully not) and then upgrade my project accordingly. I will try to list any breaking changes in this thread for anyone else who needs to do this upgrade.

**Comment by tjrobinson** [comment]
@JellyMaster Thanks, that would be useful as I am in a similar situation. If I get there first, I'll also share what I find.

**Comment by brockallen** [comment]
Ok, so no promises, but I don't think there have been any schema changes recently.

**Comment by tjrobinson** [comment]
@JellyMaster @brockallen I've confirmed that the schema hasn't changed between v7.5.0. and v8.2.1 by...

- Checking out the v7.5.0 tag, building and running the SingleTenantWebApp sample with a local SQL server connection string and using the "Generate scripts..." command in SQL Server Management Studio to dump the schema to a file
- Doing the same for the v8.2.1 tag
- Comparing the two outputs in a text diff tool

**Comment by brockallen** [comment]
Thanks for doing that @tjrobinson

**Comment by JellyMaster** [comment]
@tjrobinson Thanks for this. Big help as a starter and it also seems that using Just a simple implementation of the solution eg no 2fa seems to be working without any further changes. 

eg. I have been able to do the following: 
This is based from the simple web application (demo as a base)
(Client Application) 
1) Log in through my existing login page (No code change required)
2) Reset Password (No code change required)
3) Email's for all resets sent out and reset password api's worked as expected. (No code changed required) 


(Admin Site for managing users) 
1) Listed all users as expected (no code change required) 
2) Log in working as expected (same code base as client application) 
3) Able to Deny login (no code change required) 
4) Close Account (No code change required) 
5) Create New Account (No code change required) 
6) Close a none accessed account (delete it) (No code change required) 
7) Assigning claims to user (no code change required) 

So it does seem that in the implementation that I am using the update has worked perfectly fine. 

So currently it seems that what ever changes have occurred since 7.1 to 8.2 either are features I am not using or the changes have not been breaking changes and expected behaviour is working as expected. 

If I do find any issues I will get back to you.
