### ISSUE TITLE
How do I reset the activity timer?

### ISSUE THREAD

**Issue by bitzblitz** [brockallen/BrockAllen.MembershipReboot#499]
My Web application logs out users even though they are active in the site. I can't find any documentation on how to reset the activity timer so they are not logged out while actively using the site.

**Comment by brockallen** [comment]
This is more up to your application and how you're doing cookies. MR has samples that work with the WIF SAM and the Katana Cookie middleware... but neither is "owned" my MR -- you still need to configure them.
