### ISSUE TITLE
How to enable tracing to show up in WebApi Owin project?

### ISSUE THREAD

**Issue by kenster85** [brockallen/BrockAllen.MembershipReboot#501]
Sorry if this is a noob question but i'be been trying all day to try and get the MembershipReboot trace messages to appear when debugging my project. 
I'm able to see my own trace messages but nothing from MembershipReboot.

**Comment by kenster85** [comment]
Figured it out.
Just had to add a switch in the web.config.
Hope this helps others:
<system.diagnostics>
    <switches>
      <add name="MembershipReboot" value="Verbose"/>
    </switches>
  </system.diagnostics>

**Comment by vinneyk** [comment]
Any ideas how to get this working with ASP.NET 5 / Core? I've tried adding a similar structure to the `appsetting.json` file but no trace statements are being displayed for MR. Here's the JSON:

    "system": {
      "diagnostics": {
        "switches": {
           "add": {
          "name": "MembershipReboot",
          "value": "Verbose"
           }
        }
      }
    }

**Comment by brockallen** [comment]
This would be another thing to change for ASP.NET Core -- how MR does logging. So many new things for the new scenario.

**Comment by vinneyk** [comment]
It's not entirely incompatible; at least I don't _think_ it is. I was able to output a Trace log from within my project by writing something along the lines of `Trace.WriteLine("I have nothing to say.")`. I'll do some further testing with the `TraceSource` object as is used by MR. However, I believe I'm just missing the equivalent of the config noted above to add the trace switch. The answer's out...
