### ISSUE TITLE
Authenticate External Account (i.e. Google)

### ISSUE THREAD

**Issue by chrisaswain** [brockallen/BrockAllen.MembershipReboot#503]
I currently have an OWIN OAuthAuthorizationServerProvider implementation that lets my users get an Access_Token when they pass in their username and password.  It's essentially logging them in.  In the process, I use the Authenticate method of my CustomUserAccountService which inherits from UserAccountService so I get the Authenticate method.  

Now I'm implementing the OAuth 2 assertion flow using the Google JWT ID_Token received when the user authenticates via Google.  I can validate the Google token and get the user account object from my membership database using the ID inside the Google JWT along with the GetByLinkedAccount method.  However, this just gets the account.  It doesn't authenticated it like the Authenticate method does.  Since I don't have the username/password and I just have the Google ID and provider string, what is the correct way to Authenticate the user to make sure their account in my membership database is still active?

**Comment by chrisaswain** [comment]
Maybe it would make sense to refactor the protected Authticate(TAccount account, string password) method into an AuthenticateAccount and VerifyPassword method so that the AuthenticateAccount method could accept just the account and run the validation logic.  Then the existing Authenticate method could just call the VerifyPassword like it does now and also call the AuthenticateAccount method.  That would allow for cases of external linked account to authenticate an account without requiring a password.  I would make AuthenticateAccount a protected method like Authticate(TAccount account, string password) with a signature of AuthticateAccount(TAccount account), then I could implement an AuthenticateLinkedAccount public method that internally calls the AuthenticateAccount method.  What do you think?

**Comment by chrisaswain** [comment]
I created this method as a stopgap:

```
        /// <summary>
        /// Similar to the protected method Authenticate, this method authenticates a user account.
        /// Unlike the protected Authenticate method, this method does not verify a password.  
        /// This method is to be used in cases where the user account was found via a linked account
        /// such as a call to GetByLinkedAccount.  
        /// </summary>
        /// <param name="account">A CustomUserAccount object.</param>
        /// <returns>Returns true if the account is active and can be used.  Returns false if not. </returns>
        public bool AuthenticateLinkedAccount(TAccount account)
        {
            Tracing.Verbose("[UserAccountService.Authenticate] for account: {0}", account.ID);

            bool result = false;

            try
            {
                if (!account.IsLoginAllowed)
                {
                    Tracing.Error("[UserAccountService.Authenticate] failed -- account not allowed to login");
                    this.AddEvent(new AccountLockedEvent<TAccount> { Account = account });
                    return false;
                }

                if (account.IsAccountClosed)
                {
                    Tracing.Error("[UserAccountService.Authenticate] failed -- account closed");
                    this.AddEvent(new InvalidAccountEvent<TAccount> { Account = account });
                    return false;
                }

                if (Configuration.RequireAccountVerification &&
                    !account.IsAccountVerified)
                {
                    Tracing.Error("[UserAccountService.Authenticate] failed -- account not verified");
                    this.AddEvent(new AccountNotVerifiedEvent<TAccount>() { Account = account });
                    return false;
                }

                Tracing.Verbose("[UserAccountService.Authenticate] authentication success");
                account.LastLogin = UtcNow;
                this.AddEvent(new SuccessfulPasswordLoginEvent<TAccount> { Account = account });

                if (account.AccountTwoFactorAuthMode != TwoFactorAuthMode.None)
                {
                    Tracing.Verbose("[UserAccountService.Authenticate] doing two factor auth checks: {0}, {1}", account.Tenant, account.Username);

                    bool shouldRequestTwoFactorAuthCode = true;

                    GetTwoFactorAuthToken getToken = new GetTwoFactorAuthToken() { Account = account };
                    ExecuteCommand(getToken);

                    if (getToken.Token != null)
                    {
                        Tracing.Verbose("[UserAccountService.Authenticate] GetTwoFactorAuthToken returned token");

                        var verified = VerifyTwoFactorAuthToken(account, getToken.Token);
                        Tracing.Verbose("[UserAccountService.Authenticate] verifying token, result: {0}", verified);
                        shouldRequestTwoFactorAuthCode = !verified;
                    }

                    if (shouldRequestTwoFactorAuthCode)
                    {
                        if (account.AccountTwoFactorAuthMode == TwoFactorAuthMode.Certificate)
                        {
                            Tracing.Verbose("[UserAccountService.Authenticate] requesting 2fa certificate: {0}, {1}", account.Tenant, account.Username);
                            result = RequestTwoFactorAuthCertificate(account);
                        }

                        if (account.AccountTwoFactorAuthMode == TwoFactorAuthMode.Mobile)
                        {
                            Tracing.Verbose("[UserAccountService.Authenticate] requesting 2fa mobile code: {0}, {1}", account.Tenant, account.Username);
                            result = RequestTwoFactorAuthCode(account);
                        }
                    }
                    else
                    {
                        Tracing.Verbose("[UserAccountService.Authenticate] setting two factor auth status to None");
                        account.CurrentTwoFactorAuthStatus = TwoFactorAuthMode.None;
                    }
                }
            }
            finally
            {
                UpdateInternal(account);
            }

            Tracing.Verbose("[UserAccountService.Authenticate] authentication outcome: {0}", result ? "Successful Login" : "Failed Login");

            return result;
        }

```

I also had to override/new the following properties on my CustomUserAccount that inherits from RelationalUserAccount since the new method needs to modify them and they are inaccessible:

```
        public virtual new DateTime? LastLogin { get; protected internal set; }

        public virtual new TwoFactorAuthMode CurrentTwoFactorAuthStatus { get; protected internal set; }
```

**Comment by brockallen** [comment]
So to address your first question, you would need to have your OAuth token endpoint issue a access token based upon the google id token. If you're using the Microsoft middleware as the OAuth authorization server, then you'd need to contact them for support on how to do that.

**Comment by brockallen** [comment]
I'm not clear on why the code in MR needs to change to accommodate the code that's issuing your token. If you're able to determine the user from the google id token, then that's all the role that MR takes -- you can find the account from the linked provider/id and now you have the account, you just need to issue the claims. There's no need to call Authenticate since that's for password authentication. The valid id token from google is just as good as the user's password.

**Comment by chrisaswain** [comment]
I wanted to call Authenticate because it seems to have validation logic to determine if the account not only exists, but is verified, active/closed, login allowed, etc.  As you can see in my posted code above, I just took out that logic and created my own new AuthenticateLinkedAccount method that will run those checks on the account found based on the provider string and id.  

I was just thinking it might make sense to pull out the logic that does that checking in the Authenticate method into another protected method so it can be used by Authenticate and any methods users want to add like my AuthenticateLinkedAccount method.  

Hopefully I'm making sense and not misunderstanding how the code should be used.

**Comment by brockallen** [comment]
Right... ok, now it's more clear. For external accounts this was done via the AuthenticationService class and its SignInWithLinkedAccount, but that was certainly designed to do two things: do the checks you said, and issue a login cookie. Your scenario makes that more of a challenge since you're not issuing a cookie in the OAuth token service scenario,

So solution? Not sure...

**Comment by chrisaswain** [comment]
Looking forward to seeing what you come up with.  In the meantime, I have my work-around, but it would be nice to be able to use MR code that stays up to date rather than my cheap knock off.

**Comment by brockallen** [comment]
Yep, understood. Not sure what (if anything) will be done, but I'll leave this open as a reminder to think about it.

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
