### ISSUE TITLE
Invalid NameIdentifier on use GetUserID with Identity Server Bearer Token Authentication

### ISSUE THREAD

**Issue by julianpaulozzi** [brockallen/BrockAllen.MembershipReboot#504]
Probably should be some my ignorance.

When configuring with success authentication using the "Thinktecture.IdentityServer3" with "MembershipReboot" and use the extension method of "UseIdentityServerBearerTokenAuthentication" the IPrincipal not has some data when authenticated by "Cookie like SingleTenant" or something has not been mapped in my factory.

So when calling a method of with "Principal.GetUserID ()" get the error "Invalid NameIdentifier".

Something I should check in the examples or any tips?

**Comment by brockallen** [comment]
Check the list of claims you have and the claim types. Something in the token is not lining up with the expectation.

**Comment by julianpaulozzi** [comment]
And this would go in "Client" to "IdentityServerServiceFactory"?
Another thing I noticed is that when authenticating so is not called my ClaimsTransformer. More there is nothing there that can cause lack for now.

**Comment by brockallen** [comment]
Well, if the GetUserID() you're using is the one from MR, then it's expecting a claim of type NameIdentifider, but in the WebAPI with the UseIdSvrBearerToken middleware, it's creating a claim of type sub. The claim types are different.

**Comment by julianpaulozzi** [comment]
At exactly this, the guid is in "sub", and the code below does not seem to affect anything this.


    JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>
    {
        { Thinktecture.IdentityManager.Constants.ClaimTypes.Subject, System.Security.Claims.ClaimTypes.NameIdentifier }
    };

Authentication with "UseOpenIdConnectAuthentication" exposes the "Notifications" that could use to transform a claim, however is not the case as the "UseIdentityServerBearerTokenAuthentication" does not.

**Comment by brockallen** [comment]
So then why not just look for the sub claim directly? Do you need to use the GetUserID extension method?

**Comment by julianpaulozzi** [comment]
Yes this is a minor problem. 
Besides this claim, I use other claims (not mapped in this case) of "Principal" (populated from claims transformer) in some algorithms that can be problematic.
Anyway I am studying the case.
Thank you for your attention.
