### ISSUE TITLE
VerificationKeyPurpose.VerifyAccount set but not checked?

### ISSUE THREAD

**Issue by bitzblitz** [brockallen/BrockAllen.MembershipReboot#505]
I see
key = SetVerificationKey(account, VerificationKeyPurpose.VerifyAccount, state: account.Email);

but I never see
!IsVerificationKeyValid(account, VerificationKeyPurpose.VerifyAccount, key) 

and consequently my account creations don't verify. Am I missing something? I had to change the first line to use .ChangeEmail to get things working.

**Comment by brockallen** [comment]
You need to provide more context to your question.

**Comment by bitzblitz** [comment]
When I create and account in MR 7.2 a key is created in Init with:


key = SetVerificationKey(account, VerificationKeyPurpose.VerifyAccount, state: account.Email);

but when the account is verified this is called:

if (!IsVerificationKeyValid(account, VerificationKeyPurpose.ChangeEmail, key))

so the key is invalid.

This seems to be fixed in 8.2, so I’m going to try using that version.






Sent from Windows Mail





From: Brock Allen
Sent: ‎Friday‎, ‎March‎ ‎6‎, ‎2015 ‎8‎:‎37‎ ‎AM
To: brockallen/BrockAllen.MembershipReboot
Cc: John Dubois





You need to provide more context to your question.

**Comment by brockallen** [comment]
Yep, please check 8.2 and let me know how it goes.

**Comment by bitzblitz** [comment]
Integrated the 8.2.1 package and tested account creation and email change. Both worked.






Sent from Windows Mail





From: Brock Allen
Sent: ‎Friday‎, ‎March‎ ‎6‎, ‎2015 ‎11‎:‎56‎ ‎AM
To: brockallen/BrockAllen.MembershipReboot
Cc: John Dubois





Yep, please check 8.2 and let me know how it goes.

**Comment by brockallen** [comment]
Ok, good news then.
