### ISSUE TITLE
Expiry indicator in confirmation e-mails.

### ISSUE THREAD

**Issue by bitzblitz** [brockallen/BrockAllen.MembershipReboot#506]
When users receive their confirmation e-mail messages they can't know that they will time out. There should be a mention like "this key will time out in 20 minutes. After that you will have to reinitiate your request". or "This confirmation link is valid until 13:30 your time.". They latter would require MR to know the time zone of the user, but that could be a parameter or part of the user account.

**Comment by brockallen** [comment]
You can add this to the email messages -- just do your own formatter.

**Comment by bitzblitz** [comment]
Is there documentation on this or on getting the expiry time?

Sent from my Windows Phone
________________________________

**Comment by brockallen** [comment]
Not sure there are docs, since the "configurability" of expiration was added later. It's on the MR Config class, IIRC.

**Comment by brockallen** [comment]
Yep, `SecuritySettings` (the class for loading settings from .config) and `MembershipRebootConfiguration` (the in-mem settings passes to the `UserAccountService`) both have a `VerificationKeyLifetime` property to control that.
