### ISSUE TITLE
Different Verification Key Lifetime For New Account & Reset Password

### ISSUE THREAD

**Issue by parkinsona** [brockallen/BrockAllen.MembershipReboot#507]
Hi,

I have a requirement where our client would like the Verification Key for a new account to be active for several days. Our client will set users up themselves, and it may take a week for the user to click on the link.
They still want a short (20mins) reset password verification key.

At the moment, I'm going to add 2 app settings for the different timeouts, and set the VerificationLeyLifetime of my config prior to calling VerifyEmailFromKey or ResetPassword.

Is it possible to have a 2nd config item added for this?

**Comment by brockallen** [comment]
Why don't you just create a different MR config and thus different UserAccountService for the other scenario>

**Comment by parkinsona** [comment]
Hi Brock,

I had already coded my suggestion up, but I redid it as per your suggestion with a 2nd MR config. It differs by just the VerificationKey expiry.

Would be nice if there was a 2nd attribute to set these separately by default.
I'm sorted for now :)
