### ISSUE TITLE
Account Event handling and TransactionScope

### ISSUE THREAD

**Issue by stefanveliki** [brockallen/BrockAllen.MembershipReboot#508]
Hi,

This is more of a question and request for suggestions...

Our web api controller code executes within a transaction scope.  Some of that code is calling MR's account create API. Those methods raise events before and after the repo call is done. One of the handlers of those events is to send email out to the new user.

How should I handle a scenario where the transaction scope fails. At that point of time, the event has been raised, handled, and email has been sent, yet, the record doesn't exist in the database.

I was thinking, if the RaiseEvents was not private, I would be able to bypass the .Add call for the repo and call the RaiseEvents on my own terms.

Any thoughts, suggestions?

Thank you

**Comment by brockallen** [comment]
Perhaps use a transactional queue.

**Comment by stefanveliki** [comment]
Interesting, I am not even slightly familiar with transactional queues, but I'll certainly read a bit more about them. 
Thanks
