### ISSUE TITLE
Membership Reboot without creating database/ tables

### ISSUE THREAD

**Issue by skuvnar** [brockallen/BrockAllen.MembershipReboot#509]
Hi, I am integrating membership reboot with my current app. In development, the SQL server account was able to create the database/ relating tables.  However I dont have these permissions in production.

So just wondering if there are any setup SQL scripts/ or configurations that could be used in a environment where I dont have permissions to create databases or tables.

Hope this makes sense. Could you please help.
Thanks

**Comment by brockallen** [comment]
There's a .sql file in the EF NuGet's folder structure (in ~/packages).

**Comment by skuvnar** [comment]
Ah.. thanks for that.
