### ISSUE TITLE
Reset the FailedLoginCount

### ISSUE THREAD

**Issue by raghubhat4u** [brockallen/BrockAllen.MembershipReboot#514]
Hi,

I am using Brockallen for Authentication purpose. I have a requirement where Admin can reset the number of failed login attempts to 0 to allow user to login without blocking further. Could you please suggest how to achieve this. 

I am using version 8.1

Thanks,
Raghu

**Comment by brockallen** [comment]
I don't think I have a public API to do that. Feel free to add one and send a PR.

**Comment by raghubhat4u** [comment]
Thank you..
