### ISSUE TITLE
Question: why not RemoveEventHandler or way to specify the order of execution of events.

### ISSUE THREAD

**Issue by stefanveliki** [brockallen/BrockAllen.MembershipReboot#515]
Was there a reason to not have a “RemoveEventHandler”, as opposite to “AddEventHandler”?
Also, what are your thoughts execution order of event handlers? I am attempting to force the execution of a handler defined in a derived project ahead of the handler which is defined in the base project.
Thank you

**Comment by brockallen** [comment]
I didn't add a Remove because the Config (and thus the event handlers) is shared across all instances of the user account service. If you need a different set of event handlers for a different scenario then use a different config.
