### ISSUE TITLE
ChangePasswordFromResetKey doesn't clear failedLoginCount

### ISSUE THREAD

**Issue by parkinsona** [brockallen/BrockAllen.MembershipReboot#516]
Hi,

I have had a user who locked themself out recently, and they reset their password. However, they couldn't log in again until their lockout period had expired. 

I call the following to reset the user's password:
``` c#
_userService.ChangePasswordFromResetKey(model.VerificationKey, model.NewPassword)
```

From what I can see, this calls SetPassword(account, newPassword) which does not reset the failed login count. 

I see the API has a SetPassword(accountId) which will reset the failurecount.
Is there a reason why ChangePasswordFromResetKey doesn't reset the failure count? 

Also, is there a way to tell the user that their account is locked when their login fails. I'm currently using MR in the context of identityserver, and it just tells them the user name password is incorrect. Perhaps this is by design?

**Comment by brockallen** [comment]
fixed w/ PR

**Comment by parkinsona** [comment]
Thanks for this update. It looks good now.
I noticed the following in the releast notes for v8.3: 
```
overloaded authN APIs to indicate authentication result (e.g. locked account, failed credentials, etc)
```

Does this mean it would be possible to show  an IdentityServer user that their account is locked?

**Comment by brockallen** [comment]
Yep

**Comment by parkinsona** [comment]
Is there something I need to update in IdentityServer to make this happen?
In the UI it kept showing me username or password invalid after the account was locked.
I did have the "account in lockout due to failed login attempts" in the event log though.

**Comment by brockallen** [comment]
Yes, you'd need to implement the user service to use these new APIs.

**Comment by parkinsona** [comment]
Thanks for that. At the moment, I don't really need it. But it's good to have it for the future.
