### ISSUE TITLE
Duplicate message body for Account creation

### ISSUE THREAD

**Issue by raghubhat4u** [brockallen/BrockAllen.MembershipReboot#517]
Hi,

I am getting account verification email. But the message body is duplicated

This is the body:  
This message is to confirm your email address with Raptor v6. Username: xxxxx@outlook.com Email: xxxxxx@outlook.com Please click here to confirm your email address: http://localhost:3640/User/Change/Confirm/PRKJpOkOvxlv0MhLsqG4gÜ4 If this This message is to confirm your email address with Raptor v6. Username: xxxx@outlook.com Email: xxxx@outlook.com Please click here to confirm your email address: http://localhost:3640/User/Change/Confirm/PRKJpO 

Any work around for this. Please suggest

Thanks,
Raghu.

**Comment by brockallen** [comment]
I just tested this and I'm not seeing what you describe. You should debug into your email formatting code.

**Comment by raghubhat4u** [comment]
Yeah.. it was my bad..
