### ISSUE TITLE
A claim of type 'sub' was not present on the provided ClaimsIdentity.

### ISSUE THREAD

**Issue by srberndt** [brockallen/BrockAllen.MembershipReboot#521]
I'm using the MembershipReboot assemblies to create a membership manager for my IdentityServer3 based authentication/authorization system.  I started with one of the samples and had great success at turning it into a system that fits my requirements.  After adding an AuthorizationManager class and  [ResourceAuthorize(...)] attributes to my controller methods, I started getting the error:

"A claim of type 'sub' was not present on the provided ClaimsIdentity"

The post at  https://github.com/IdentityModel/AuthorizationServer/issues/61  is right on target to my issue.  However, I don't see where or how I add a "Sub" claim to the token.

Any help I can get with this would be greatly appreciated.  Thank you.

**Comment by brockallen** [comment]
Sorry -- was traveling and this issue fell off my radar.

IdentityServer needs a `sub` claim and you'd map that from the `UserAccount.ID` property of MembershipReboot. I'd suggest looking at this code to get an idea how to implement the user service in IdentityServer:

https://github.com/IdentityServer/IdentityServer3.MembershipReboot/blob/master/source/MembershipRebootUserService/MembershipRebootUserService.cs

**Comment by brockallen** [comment]
Also, this is not really an issue with MembershipReboot, so I'll close it. If you have more questions, open an issue in the more appropriate repo.
