### ISSUE TITLE
Email verification link already used when user receives email

### ISSUE THREAD

**Issue by NanosoftDK** [brockallen/BrockAllen.MembershipReboot#522]
I have an issue with some users, that when they receive their link in an email, it is already used.

In the web server logs i can see the link is used from a completely different ip, than the user has.
My guess is that some email scanner service visits the link to check for malware.

I have a setup where I create a user with a blank password, and no password is sent in the email, when they use the verification link, i redirect them to change their password, in that way i force the user to pick there own password.

One solution could be to allow multi use of the link, but that would degrade the security. 

Any thought about how to solve this?

This could be the same issue as #482 is experiencing.

**Comment by brockallen** [comment]
Make the page POST back with JS -- the automated scanners will not submit the page.

**Comment by NanosoftDK** [comment]
thanks, i will try to implement that.
