### ISSUE TITLE
Support for read only db 

### ISSUE THREAD

**Issue by EsbenSkovPedersen** [brockallen/BrockAllen.MembershipReboot#524]
We would like to geo replicate the db for membership reboot used with identityserver for higher availbility on microsoft azure.

It seems like it is currently not possible because last login time i written to the db when authenticating.

Are there any work arounds for this scenario?

**Comment by brockallen** [comment]
i guess you could override the Update methods to no-op on those read only deployments. but then how do you do brute force protection? or password reset?
