### ISSUE TITLE
"error occurred" message shown when accessed with /admin in azure websites.

### ISSUE THREAD

**Issue by vinaykasireddy** [brockallen/BrockAllen.MembershipReboot#526]
I am getting errors while trying to access the IdentityManager configured with Membershipreboot via /admin. The error message is in json format and it is just "error occurred". Can't figure out what was the cause. Is there any way to enable the tracing?

What we have tested so far:
------------------------------------
1) Working in local but not when hosted in azure website. 
2) /identity is working in azure, but not /admin. (Site is being accessed via https)
3) SQL connection string settings are given properly and tested individually. No issues.
4) No cert issue as the same cert provided in the documentation is used. (Proof: /identity page is showing).

**Comment by brockallen** [comment]
This is the wrong repo for IdentityManager. It's here: https://github.com/IdentityManager/IdentityManager

Please check the docs on the security config: https://github.com/IdentityManager/IdentityManager/wiki/Security-Configuration

**Comment by vinaykasireddy** [comment]
Hi Allen,

Thanks for the qucik response. Not sure if you have got my point. But here are the direct links. Just access. You might get a clear cut idea where exactly the issue could be. Thanks in advance.

https://appsworldidentity.azurewebsites.net/identity (WORKING)
https://appsworldidentity.azurewebsites.net/admin (NOT WORKING)

**Comment by brockallen** [comment]
Yes, I have a good idea what the issue is. That's why I suggested:

_Please check the docs on the security config: https://github.com/IdentityManager/IdentityManager/wiki/Security-Configuration_

**Comment by vinaykasireddy** [comment]
Hi Allen,

I tried to put the below piece of code. Is it deprecated as i do not found this property in Thinktecture.IdentityManager.Configuration.IdentityManagerOptions class.

SecurityConfiguration = new HostSecurityConfiguration
{
     HostAuthenticationType = "Cookies"
}

**Comment by vinaykasireddy** [comment]
Hi Allen,

Solved the issue now. The difference is instead of using IdentityManager, i used Thinktecture.IdentityManager.

But why is this confusion for us? I thought since Thinktecture.IdebtityManager is stable i used it.

**Comment by brockallen** [comment]
Please open an issue in the correct repo.
