### ISSUE TITLE
Single Tenant Web App Sample -- how do I prevent it from clearing the MR database every time I deploy it to a test server?

### ISSUE THREAD

**Issue by schmosef** [brockallen/BrockAllen.MembershipReboot#527]
I'm guessing that some command is resetting the database. How do I turn that off?

**Comment by schmosef** [comment]
Actually, it looks like it clears the database every time the application restarts. How do I stop that from happening?

**Comment by brockallen** [comment]
Configure your EF code how you want it (with `Database.SetInitializer`).

**Comment by schmosef** [comment]
Sorry if this is a stupid question but I don't understand what my configuration options are.

Is this documented somewhere?

I tested the IdentityManger.MembershipReboot demo project and it created the database the first time it ran but it does not clear the database when the app is restarted. And it does not even have a call to Database.SetInitializer as far as I can see.

Should I just comment out the line?

**Comment by joffies** [comment]
Its because you probably are setting it in the web.config file too. Remove it from either the web.config or the RegisterServices section.
