### ISSUE TITLE
Unable to send verification email

### ISSUE THREAD

**Issue by f0rt** [brockallen/BrockAllen.MembershipReboot#529]
HI,

I'm trying to send verification mail but something is wrong with my code.
1. I've configured in web.config the following settings `<mailSettings>` and I'm able to send a message with `System.Net.Mail.SmtpClient`
2. I'm using the following code to request verification:
 `var acc = userAccountService.GetByEmail("myemail@gmail.com");
 userAccountService.RequestAccountVerification(acc.ID);`

I'm not getting an error and I never receive an verification email. So what am I missing here?

Thanks,
f0rt

**Comment by f0rt** [comment]
Actually, I was able to setup and run IdentityServer3 / MembershipReboot / IdentityManager. Is there build in user self-registration pages or I need to create one myself?

**Comment by brockallen** [comment]
This API raises the `EmailChangeRequestedEvent` event -- are you handling that?

**Comment by brockallen** [comment]
As for IdSvr, no -- nothing in IdSvr does registration, so you have to build that yourself.

**Comment by f0rt** [comment]
Thanks. It works now.
