### ISSUE TITLE
Allow to create account with initial claims

### ISSUE THREAD

**Issue by girtsl** [brockallen/BrockAllen.MembershipReboot#532]
Hi, 

please consider the possibility to pass in a collection of claims when creating a new user account.
The goal of this feature would be to provide more context about the account to services down the line like EmailMessageFormatter but it could also be useful in other ways.

In order to provide our users with localized experience we allow them to select their preferred language upon registration which we then store in a claim. Our custom email message formatter then uses this claim to pick an email template in user's selected language. This works for all but AccountCreated event as the claims can only be added after account has been created.

I guess this specific case could also be done by overriding the UserAccount (RelationalUserAccount in our case) class and adding an additional property, then feeding a pre-populated account instance to the CreateAccount method, but a claim suits us much better.

Do you think something like this would be possible?

**Comment by brockallen** [comment]
Sure, not a bad idea. Feel free to fork and prototype something. We accept PRs.
