### ISSUE TITLE
Calls to ValidateEmail returning server 500 error

### ISSUE THREAD

**Issue by StateBarofArizona** [brockallen/BrockAllen.MembershipReboot#533]
I have a form that asks for the username and password the user would like to use to create their new account.  I use AJAX to post to a Register controller.  That passes to CreateAccount which uses ValidateEmail to check MembershipReboot to see if the email has already been used, the password is the correct format, etc.  I am seeing the ValidationException being passed to Elmah but the AJAX call is returning a server 500 error with this validation exception rather than content I can then pass to my user and display on the form.

**Comment by brockallen** [comment]
Sorry -- somehow I missed this issue.

MR will throw `ValidationException`s so you'd need to catch that and translate that back to some logical error to your Ajax client.
