### ISSUE TITLE
Roles in membershipReboot

### ISSUE THREAD

**Issue by tarant** [brockallen/BrockAllen.MembershipReboot#536]
Is it possible to configure app specific roles? We have users exists for multiple applications, but roles can be specific for each applications. That means that the role Admin for app1 is different than the role Admin for app2. But user1  is active for all applications just with different roles.
Is it possible to implement using claims?

Thanks.

**Comment by brockallen** [comment]
Sorry -- somehow I missed this issue.

Roles are just claims. So if you have one app that only needs a few claims, then filter them when the user is logging in. There's a claim filter map command on the MR config for this sort of thing.
