### ISSUE TITLE
Dapper Example

### ISSUE THREAD

**Issue by TDK1964** [brockallen/BrockAllen.MembershipReboot#538]
Hi, Has anyone implemented MR using Dapper, I'd like to use MR with Dapper but am struggling to work out how to do it.

**Comment by brockallen** [comment]
Sorry, I don't even know what dapper is. Maybe someone else has though.

**Comment by TDK1964** [comment]
Dapper is a lightweight ORM https://github.com/StackExchange/dapper-dot-net

**Comment by brockallen** [comment]
If Dapper supports proper IQueryable semantics, then you could derive your Dapper repository from the QueryableUserAccountRepository. If not, then you'd need to implement the interfaces yourself manually.

**Comment by TDK1964** [comment]
Any chance of a quick example of implementing the interfaces manually?

**Comment by brockallen** [comment]
There is the EF course (of course) and there are samples of no-sql in the ~/samples folder.

**Comment by TDK1964** [comment]
Unfortunately EF is too slow.

**Comment by brockallen** [comment]
You asked examples of implementations and I pointed you at the ones we have -- EF, NHibernate, Mongo, and RavenDb. Once you have a Dapper implementation I'm happy to include it as a sample or link to it from here.

**Comment by TDK1964** [comment]
Unfortunately, I don't have the skills to be able create a Dapper version :( 
I guess I'm going to have to resort to the default ASP.NET Identity solution which is a shame :(

**Comment by brockallen** [comment]
So there's a Dapper repository implementation for ASP.NET Identity?

**Comment by TDK1964** [comment]
There is a basic version at http://blog.markjohnson.io/exorcising-entity-framework-from-asp-net-identity/

**Comment by tjrobinson** [comment]
@TDK1964 Which specific bits are too slow?

**Comment by TDK1964** [comment]
@tjrobinson Have a look at the performance comparison on the Dapper site https://github.com/StackExchange/dapper-dot-net

**Comment by tjrobinson** [comment]
@TDK1964 Sorry, I should have been more specific. I meant which bits of MembershipReboot are running slowly using EF? Or is it just generally "too slow"?

**Comment by brockallen** [comment]
Yea, I think the remarks might just be in general (EF vs. Dapper). I guess what's a more honest assessment is using MR with both DB implementations and comparing those. Also, the thing is, the identity management library is infrequently used -- only at login time typically, so if you're only talking a few percentage difference then perhaps the effort on optimization is  better spent elsewhere. *shrug*

**Comment by TDK1964** [comment]
As Brock says, I was referring to EF vs Dapper. The speed of MR was perfectly acceptable however, my application uses Dapper and I didn't want to have both running.  I would have loved to use MR but just don't have the skills or time to create a Dapper version.

**Comment by brockallen** [comment]
Seems like this issue can be closed now.
