### ISSUE TITLE
Question - allow a handler to terminate processing of that event?

### ISSUE THREAD

**Issue by synesthesia** [brockallen/BrockAllen.MembershipReboot#539]
In my implementation I am handling the account created event in order to post account details to an external system (a CRM), and get some additional data which I use to create additional claims

If an error occurs I would like to cease the processing of that event, so that I can then do some corrective action (typically display an informative error message and clean up the database).

I've cheated this slightly by making sure this handler is added first, so it should process first, but not sure if that is the best way to do it consistent with the design.

Any recommendations please Brock?

**Comment by brockallen** [comment]
How do other event bus systems handle this?

**Comment by synesthesia** [comment]
Good question, haven't researched.

**Comment by brockallen** [comment]
Any update?

**Comment by synesthesia** [comment]
I changed my implementation - provisioning in the remote system in the validation stage for IdSrv.
