### ISSUE TITLE
UserAccountService ForceEmailChange method

### ISSUE THREAD

**Issue by kendaleiv** [brockallen/BrockAllen.MembershipReboot#540]
We're in a scenario where we want to allow individuals using our backend management tool to immediately force change an email address for a user.

The implementation would look similar to [src/BrockAllen.MembershipReboot/AccountService/UserAccountService.cs#L1735-L1765](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/0a87fd5144b5277d5618e82ec3362721047f6197/src/BrockAllen.MembershipReboot/AccountService/UserAccountService.cs#L1735-L1765), but instead forcing the change to take place immediately.

I'm wondering if this would be a desired feature? The method could be named `ForceEmailChange`, unless you'd like a different name.

--

**Note:** Some resistance is encountered creating a `ForceEmailChange` method in our subclass implementation of `UserAccountService<TAccount>` due to protected internal setters.

**Comment by brockallen** [comment]
So you want to have an admin to hit a button that emails the end user to change their password?

**Comment by kendaleiv** [comment]
Basically, a text box and a button that will immediately force change a user's email address. The user does not need to verify the change.

**Comment by brockallen** [comment]
There's already a SetConfirmedEmail API IIRC. You'd user this API from your trusted admin UI.

**Comment by kendaleiv** [comment]
Ah, it looks like that'll do it, awesome! Thanks!

**Comment by brockallen** [comment]
We're full of surprises.
