### ISSUE TITLE
SingleTenantOwinSample - Possible bug

### ISSUE THREAD

**Issue by dealproc** [brockallen/BrockAllen.MembershipReboot#542]
Is this correct:
https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/samples/SingleTenantOwinSystemWeb/SingleTenantOwinSystemWeb/Areas/UserAccount/Controllers/RegisterController.cs#L44

It seems as if, based on the way the controller works, that the user would need to be logged in to trigger the verification the way that it's setup.

**Comment by DavidChristiansen** [comment]
The controller is dressed with the [AllowAnonymous] attribute, which means that all methods will not require an authenticated context does it not?

**Comment by brockallen** [comment]
@DavidChristiansen right -- the allow anon on the controller will let in anon users.

**Comment by dealproc** [comment]
What i was getting at was (I should have grabbed line 51 instead) if you run that postback, you're not going to have an identifier going into the validation method, and it's going to fail.

**Comment by brockallen** [comment]
Ok, cleaning up old issues. I don't know what verifier, but this was working.
