### ISSUE TITLE
Fix: OWINAuthenticationService<TAccount>.GetCurentPrincipal: Discrepency between generic and non generic implementation of getPrincipal

### ISSUE THREAD

**Issue by DavidChristiansen** [brockallen/BrockAllen.MembershipReboot#543]
I believe there may be a case for making the `protected override ClaimsPrincipal GetCurentPrincipal()` methods the same for both generic and non-generic implementations of OwinAuthenticationService.  I have had to do this in an override GetCurentPrincipal in my custom OWINAuthenticationService in order to get things flowing nicely.

Instead of 

``` csharp
            var cp = context.Request.User as ClaimsPrincipal;
            if (cp == null) cp = new ClaimsPrincipal(context.Request.User);
            return cp;
```

use

``` csharp
            var u = context.Request.User;
            if (u != null && u.Identity.AuthenticationType == this.authenticationType) {
                var cp = context.Request.User as ClaimsPrincipal;
                if (cp == null) cp = new ClaimsPrincipal(context.Request.User);
                return cp;
            }
            return null;
```

See [OwinAuthenticationService](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot.Owin/OwinAuthenticationService.cs#L83-L93) and [OwinAuthenticationService<TAccount>](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot.Owin/OwinAuthenticationService.cs#L166-L171)

**Comment by brockallen** [comment]
Feel free to send a PR and I can verify it.

**Comment by DavidChristiansen** [comment]
Will do.

**Comment by DavidChristiansen** [comment]
Also maybe worth noting the typo in the method name `GetCurentPrincipal` ;)
