### ISSUE TITLE
New Feature: Add HMAC-Based One-time Password (HOTP) and Time-based One-time Password (TOTP) support

### ISSUE THREAD

**Issue by DavidChristiansen** [brockallen/BrockAllen.MembershipReboot#544]
I have added support for the HMAC-Based One-time Password (HOTP) algorithm specified in RFC 4226 and the Time-based One-time Password (TOTP) algorithm specified in RFC 6238 to enable the use of Microsoft and Google authenticator as 2fa mechanism.

Please assign to me if you want this feature brought back into github.

_ticket originally created in error [here](https://github.com/IdentityServer/IdentityServer3.MembershipReboot/issues/29)_

**Comment by brockallen** [comment]
For 2fa codes? Not sure how much effort this would be to rework MR's semantics around this... but you're saying you did this already?

**Comment by DavidChristiansen** [comment]
I have a rough working prototype which I am planning on completing and making releasable. You interested? Do you think there would be a demand for this feature?

**Comment by brockallen** [comment]
I think having an option for something other than SMS is great. Maybe we can chat over skype and see what you have.

**Comment by DavidChristiansen** [comment]
Working example ready to demonstrate.

**Comment by DavidChristiansen** [comment]
Once we have talked this over, I think can strip out the CSS changes etc so a PR is purely RFC-6238 (unless you want the UI changes aswell)

**Comment by brockallen** [comment]
I just got back from holiday, so you'll have to give me some time to get to this. Thx.

**Comment by ericlink** [comment]
It seems the fork @ https://github.com/DavidChristiansen/BrockAllen.MembershipReboot/tree/feature/RFC-6238 is not longer there... has it moved somewhere, or is there another implementation of TOTP somewhere else?

Thanks, - Eric

**Comment by DavidChristiansen** [comment]
Hi Eric, The PR was resubmitted under #594 - needs to be updated in line with recent changes but its all there.

**Comment by ericlink** [comment]
Ah great, thanks David!  We are doing a two factor project, and this is something we'll want to add.  It's great it's so close.  If we get to that point before you've gotten to it, I'll be happy to help.   Until then, we're just working hard to get version one of our project going...

**Comment by hanskhe** [comment]
Any idea about when this might be completed? It is a feature we would love to have in our system, as SMS-delivery is not very reliable in all corners of the world.

**Comment by DavidChristiansen** [comment]
@hanskhe https://twitter.com/dchristiansen/status/836609064981446656

**Comment by DavidChristiansen** [comment]
Implemented to Dev branch
