### ISSUE TITLE
Make properties/methods protected within RelativeApplicationInformation

### ISSUE THREAD

**Issue by dealproc** [brockallen/BrockAllen.MembershipReboot#547]
Possibility of making the following methods as protected (I believe protected will allow this):

`string CleanupPath(string path);`
and
`BaseUrl { get; set; }`

so that when you have to inherit the RelativeApplicationInformation/OwinApplicationInformation object to create new Urls for your application, you have the utilities to build a full Url string.

**Comment by brockallen** [comment]
Ok, done.
