### ISSUE TITLE
Is there a recommended way to avoid "Claims Collision" / Applying Claims to users

### ISSUE THREAD

**Issue by JellyMaster** [brockallen/BrockAllen.MembershipReboot#551]
This is more a question about using MR with Identity Server. (Or just claims management in general)  

With the need for different applications to have their own specific claims and other claims to be more generic eg. cross application claims like Name, Email etc. 

Is there a recommended way of handling this scenario? 

My current idea is to use the following: 
Have two classifications of claims: 

1) Profile/Descriptive claims e.g. FirstName, LastName, Phone etc.
2) Security Claims e.g. EditAllowed, ReadAllowed, CreateNewItem etc. 

In order to avoid one claim being "mistakenly" applied from one application to the next I am thinking of applying the following naming convention: 

`ApplicationName.ContextualElement.ClaimName`

So for example if we had 100 different applications they would each start off the claim name with their specific application name. e.g. `Application1.xx.yy` , `Application2.xx.yy`, `Service1.xx.yy` etc. 

Then the second element would be a contextual identifier such as Profile, Security, General etc. 

The final element would be the actual claim e.g. ProfileEdit, UpdateRecords etc. 

Now in order to manage Access Rights more easily I have two ideas: 

1) Add any new security rights (security claims) to all users and have disabled by default, then explicitly apply `Allowed` access. 
2) Only Add security rights as and when allowed access is granted. 

In my current non-ids solution I am using option **2** but I wonder if option 1 is the right way to go as this then ensures all my users have all the security claims added and then it is a simple case of switching them on and off within my User Management system rather than having to remember which users have access to these rights. 

My only concern with Option 1 is that the cookie being generated could get very large. I guess the way round this would be to have a "basic" cookie and then do a check on the server everytime for the appropriate access (although would this introduce more issues with network overhead/ performance issues) using this "remote" checking solution for every security right would allow for security changes to be registered straight away without the user needing to log out and back in again. 

So I guess this is more a open question to the community and just wondering what others are doing in this situation.

**Comment by brockallen** [comment]
In IdSvr 2.0.0 we've added the client ID making the token request to the user service get get profile API. This allows you to decide what claims to return to which client.

As for the storage of the claims and how they map to clients -- yea, MR doesn't have that concept, so your naming convention might just be as good as anything.

**Comment by JellyMaster** [comment]
It's fine Brock, I am sure you are a very busy boy with all the various conferences that seem to be occurring this year. 

Is this same feature of getting the profile data/claims for the calling app in idSvr 3.0 as well?

Well I have implemented my "solution" so we will have to see how well it works. I think the concept of it is sound but only time will tell once we have implemented it into a number of solutions. and see how flexible it is. As for forcing a refresh of the Token from the client is it possible to point me in the right direction within idSvr 3.0 to do this as it would be a nice feature to implement "under the hood" to get people the access rights straight away rather than having to log out and back in again as we are currently having to do during testing.

**Comment by brockallen** [comment]
Sorry -- I meant IdSvr3 build 2.0.0 in my prior statement.

**Comment by JellyMaster** [comment]
Is Build 2.0.0 out yet as it seems to be 1.6.2 as the latest build. 

edit: sorry I can see 2 is currently in rc1 mode. I guess we will hang on to using 1.6.2 for now as we are still getting to grips with it and changing to an rc1 version is a bit too risky at the minute. 

I will have a look into the new features and respond back via the IdSvr project if I have any issues.
