### ISSUE TITLE
Forgot password process and verification email

### ISSUE THREAD

**Issue by rhunt79** [brockallen/BrockAllen.MembershipReboot#553]
I have a inquiry regarding the intended process for forgot passwords with Membership reboot.

The process my superior's would like is click 'forgot password'  enter email, if verified and valid send verification link to account email, follow link back to secret questions pages, answer questions and upon valid response present the change password options and submission upon valid password syntax entered.

My problem stems with the UserAccountService.ResetPassword. I was using this to send the verification email and it appeared to work just fine until I got the password secrets setup and now if an account is verified and has secrets the ResetPassword function fails stating the secrets need to be answered. "This account requires a secret question and answer to reset the password."

So I am curious are you supposed to submit the answers first? This seems counter intuitive and a security risk retrieving questions without verifying through email of the user?

**Comment by brockallen** [comment]
Look at how the samples do this.

**Comment by rhunt79** [comment]
I have and if I am following correct, it appears to check if the account does not have any secrets then it submits the reset request but if it does it returns the questions to be displayed but we'd like to just send the validation email from the reset request and then have the user follow the link and return the questions at that point. Is that not possible?

**Comment by brockallen** [comment]
If the user account has secrets registered, then they must be used to reset the password. That's the whole point of the feature. Is that not the behavior you want?

**Comment by rhunt79** [comment]
yes and no. It doesn't seem very secure to enter the email address and be presented with the questions immediately without having them be directed back to their email to follow a link?  That seems to be common practice no?

**Comment by rhunt79** [comment]
Hey Brock you can close this. They wanted the order the process a little different but once I implemented how it was setup in the samples and showed them that flow they were Ok with at process.
