### ISSUE TITLE
Set MobilePhone during account registration

### ISSUE THREAD

**Issue by TheOtherOnes** [brockallen/BrockAllen.MembershipReboot#555]
I want my users to provider their mobile phone numbers during registration.  I'm using SetConfirmedMobilePhone() because MobilePhone is read only.  The problem is that calling SetConfirmedMobilePhone() causes a MobilePhoneChangedEvent and an email to be sent.  That means that every time a user registers, they get 2 emails - the registration confirmation and a "you changed your mobile phone".  This is confusing to the user because they only provided their phone number but didn't change it.  

Is there another way to do this or a way to suppress the email?

**Comment by brockallen** [comment]
This is a current limitation of the system -- it can only handle doing confirmation of one thing at a time (email vs mobile). Sorry.

**Comment by TheOtherOnes** [comment]
Thanks @brockallen.  I'm not sure what you mean "it can only handle doing confirmation of one thing at a time (email vs mobile)."  Is there any chance of added MobilePhone to CreateAccount()?  Where you thinking that MobilePhone would always be added at a later time, rather than during registration?

I thought I could just add a claim called MobilePhoneNumber during registration, but that added a record in UserClaims instead (that's a very nice feature though).

**Comment by brockallen** [comment]
MR has support for doing the confirmation process for email and mobile phone, but it uses the same column in the DB for each, so only one can be done at a time. If I could start all over again, I'd not have done it that way... it grew over time, so that's why it is the way it is.
