### ISSUE TITLE
Administrator for a group, group with access to section of site.

### ISSUE THREAD

**Issue by rbailo** [brockallen/BrockAllen.MembershipReboot#557]
I was doing some research on Identity when I came across your post with MembershipReboot, I found it very interesting to say the least. I have watched the video you recommended 2 times now and have been reading your site over and over as well as digging into your code.  I am new to MVC only be working with it for a little under a year but coming from PHP I love the standard most follow. I have a few questions if you don’t mind in reference to identity and MembershipReboot. I’m interested in creating a framework for my next big project and I am thinking of using MVC. I am slightly confused with Identity and the way I want to set my system up. Let me explain how I would like to try and set my system up. So I plan on having Registered visitors that can receive News service, registered users that have access to content, registered employees that receive alerts from the system as well as have to log in to get their email and memos from upper management, Now this application will also be a multi-tier, multitenant application.  So let’s say we have a MVC application that when I add a upper level menu item (more like a department of the site) I want to be able to apply a group to that department in the administration section, Within that group will be a group Administrator, A second in command, and users under them with roles for that specific area. The administrator for that group can add and delete members, as well as delegate roles to the users under them. Now there is still a super admin that controls all aspects of the site. Now Groups from other area cannot access the area for group 1 and vice versa. Also that group can add sub menus to the department menu they run.  Anyway I was wondering how you would handle such a project. Now this project will be a Saas application and I have not found any application that does what I am looking offer with this application.

**Comment by brockallen** [comment]
MR can support managing your users' identities and credentials. Beyond that is authorization and that's up to your app. So in short, MR is an identity management library, not an authorization framework.
