### ISSUE TITLE
Generic IMessageDelivery<TMessage>

### ISSUE THREAD

**Issue by julianpaulozzi** [brockallen/BrockAllen.MembershipReboot#558]
It would be possible to make "IMessageDelivery" generic to extend the "Message" or add SendAsHtml prop in the "Message" class?
This would allow control of the sending format in IMessageFormatter.

**Comment by brockallen** [comment]
Hmm, ok. It's a breaking change... I'll leave this as an enhancement in case other major breaking changes get added.

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
