### ISSUE TITLE
Linked Account Claims on ClaimsIdentity?

### ISSUE THREAD

**Issue by geetar85** [brockallen/BrockAllen.MembershipReboot#559]
Am I missing something or do the linked account claims not get added to the claims identity on sign in? It would be nice to be able to grab some of the Linked Account data directly from the ClaimsIdentity. Is it due to potential conflicts of claim types?

**Comment by brockallen** [comment]
Correct. But we do store the external claims just not as part of the primary claims collection. If you want them in the primary claims collection, then you can do that mapping yourself.

**Comment by geetar85** [comment]
Thanks, Brock. Is there a way in the MapClaimsFromAccount handler to determine which provider they are currently logged in with so I can only grab claims from that specific linked account?

**Comment by brockallen** [comment]
The UserAccount has a collection of the linked accounts and that has the claims.

**Comment by geetar85** [comment]
Ahh, I get it now. I was under the assumption that the LinkedAccountClaims included claims for all linked accounts, not specific to the one the user signed in with. That does the trick - thanks.
