### ISSUE TITLE
Migrations, few indexes

### ISSUE THREAD

**Issue by LorryMoller** [brockallen/BrockAllen.MembershipReboot#561]
We are using the NuGet packages for MembershipReboot and MembershipReboot.Ef. We see only one record in the migrations table (2015-06...InitialCreate...) , though from the reboot source it seems like we should have a bunch (from 2014 with v7 in the name). 

The only indexes seem to be on the primary keys. Some load testing we are doing indicates we would get much better performance with more indexes (ex Useraccount.username.) Some of the v7 migrations in git seem like they would address this.

Is there something we should be doing to support the alternate migrations/expanded indexes? I don't see anything in the "EF Configuration" article addressing this.
Thanks!

**Comment by brockallen** [comment]
Check in the ~/packages folder -- there's a SQL script to install the migrations. Or you can create the DB using the migrations update-database tool. I'd not trust the auto-created DB that EF gives you -- something about that creates the DB doesn't seem to work well with proper migrations.

**Comment by LorryMoller** [comment]
Thanks! Will try that out.

**Comment by LorryMoller** [comment]
Thanks! We worked with that and it resolved our issue.
