### ISSUE TITLE
IsInRole not work in membershipreboot

### ISSUE THREAD

**Issue by amirhp** [brockallen/BrockAllen.MembershipReboot#562]
Hi
I add role from memberhip identity manager and seems roles add as claim in databasbe but 
User.IsInRole(rolename)	
ClaimsPrincipal.Current.IsInRole(rolename)
always return false.

**Comment by brockallen** [comment]
This tells me you don't understand how IsInRole works.

**Comment by amirhp** [comment]
I know always return false. is it something i missed?

**Comment by pmbanugo** [comment]
@amirhp there is a difference between role based authorization and claims based authorization. Your application is claims aware. In claims-aware applications, the role is expressed by a role claim type. check this https://msdn.microsoft.com/en-us/library/hh545448(v=vs.110).aspx to see if it clears your misunderstanding.

**Comment by brockallen** [comment]
Also, when you call IsInRole it's checking for a claim in the claims collection. That claim type depends on how the ClaimsIdentity was created. If you're letting MR create it, then the claim type is "role" (and not ClaimTypes.Role).

**Comment by amirhp** [comment]
the role calim record seems fine so how can i check this claim exist for a user or not?

**Comment by brockallen** [comment]
How are you creating the ClaimsIdentity -- what are you using to authenticate the user? OWIN cookie authentication or WIF's SAM?

**Comment by amirhp** [comment]
Im using your groups sample.  https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/samples/Groups

**Comment by brockallen** [comment]
I don't think the groups samples even does a user login, does it?

**Comment by amirhp** [comment]
yeah

**Comment by amirhp** [comment]
It does 
userAccountService.AuthenticateWithUsernameOrEmail(model.Username, model.Password, out account)

**Comment by amirhp** [comment]
so it use SamAuthenticationService

**Comment by brockallen** [comment]
That uses the `ClaimTypes.Role` claim type for IsInRole. If you're using IdentityManager, then it's adding the role with claim type `"role"`.
