### ISSUE TITLE
Possible to configure password lockout policies per tenant?

### ISSUE THREAD

**Issue by aaronwjha** [brockallen/BrockAllen.MembershipReboot#563]
We need to set different password policies per tenant. Is this currently possible? Or will we need to do some custom work?

**Comment by brockallen** [comment]
You'd create a different MR config for different scenarios.

**Comment by aaronwjha** [comment]
I'm not sure I follow. Are you saying it is possible to apply a different MR config to each tenant within a single MR instance? I've looked over all the docs I can find and don't see how this is accomplished.

**Comment by brockallen** [comment]
Just create a new instance in your code where you know the tenant. 

Next question is where do you get the tenant from on each request?

-Brock

**Comment by aaronwjha** [comment]
Yes, this is exactly what we are trying to work out at the moment. We are planning a deployment that will support 90M users across 1.5K tenants. Any recommendations for a large deployment like this would be welcomed.

**Comment by brockallen** [comment]
So do you now understand what I'm suggesting?

**Comment by aaronwjha** [comment]
No. I feel like I'm getting close, but the implementation details are still unclear to me.

**Comment by brockallen** [comment]
So in your MVC controller, MR expect you to pass tenant as params top various APIs in MR. How does your code get that value?

**Comment by aaronwjha** [comment]
We intend to use MR as the user service for IdentityServer3. Our goal is to configure endpoints to include tenant info in the URL (e.g. https://idsrv.com/[tenant]/connect/token). We haven't worked how to make that happen.

**Comment by brockallen** [comment]
So if you're doing DI then you'll have to do some callback to create a custom MR config for the tenant from the URL.

**Comment by aaronwjha** [comment]
That did it. Thanks for the help!
