### ISSUE TITLE
MultiTendency repeated email

### ISSUE THREAD

**Issue by amirhp** [brockallen/BrockAllen.MembershipReboot#564]
IS it possible which having same email between different tenant?

**Comment by brockallen** [comment]
I don't follow.

**Comment by amirhp** [comment]
Can we have same email between different tenant like what we have in username.
which can be unique in tenant.

**Comment by brockallen** [comment]
Sure.

**Comment by amirhp** [comment]
I try to describe my problem in an other way I have members with same username across different tenants is possible to have same email address unique only in tenant and maybe repeated in other tenants.

**Comment by brockallen** [comment]
Yes, email can be specific to a tenant.
