### ISSUE TITLE
Support for async/await in the database layer

### ISSUE THREAD

**Issue by sunsided** [brockallen/BrockAllen.MembershipReboot#566]
I was trying to use a MongoDB with the `HierarchicalUserAccount` and custom database samples over [here](https://github.com/brockallen/BrockAllen.MembershipReboot/tree/e66fd67fb6179cf3b759542598f44986b95eb523/samples/NoSql/BrockAllen.MembershipReboot.MongoDb). The current MongoDB driver ditched `IQueryable` in favor of async/await, so that resulted in some trouble. Since as a result there can be no `IQueryable<CustomUser> Queryable`, `QueryableUserAccountRepository` is off the table.

I though of doing it the hard way, however `IUserAccountRepository` (and fellows) as well don't support the paradigm of returning a `Task<CustomUser>` instead of a `CustomUser`. Did I miss something or is there any way around that?

That said, I'm using ASP.NET "vNext" (beta 7).

**Comment by brockallen** [comment]
No plans right now to update this to async/await -- I'm just too busy.

**Comment by brockallen** [comment]
Closing as dup of #568
