### ISSUE TITLE
Support for Google Authenticator as another way for Two Factor Authentication

### ISSUE THREAD

**Issue by cjdutoit** [brockallen/BrockAllen.MembershipReboot#570]
Hi Brock,

Can I ask for a feature request to get support for Google Authenticator.  Would be nice to get something like this that would not cost you money like the SMS option.

Have seen this blog post, but not sure how easy it would be to plumb that into your framework 
http://www.jerriepelser.com/blog/using-google-authenticator-asp-net-identity

Kind regards
Christo

**Comment by brockallen** [comment]
So from my understanding this means that the app is generating the code, right? That would be some rework to MR to allow for the code to be generated and validated by an external app. I think there's a PR for something like this (not sure since I've not had time to look into it) https://github.com/brockallen/BrockAllen.MembershipReboot/pull/552

**Comment by woodwardmatt** [comment]
Hey Brock, I think it would mean that MR would generate a Secret key to use within Google authenticator, but that GA would be generating the Two-Factor Auth code which MR would then need to validate against the Secret key (taking into account the time step).

Was thinking that this would be an awesome addition to MR as I've been knee deep in MR, IdentityServer & Identity Manager this week :) Not sure what the implication of the change would be on the login flow for IdentityServer though.

**Comment by woodwardmatt** [comment]
Yep this request matches with PR in #544

**Comment by brockallen** [comment]
Can we close this if it's a dup of another issue?

**Comment by cjdutoit** [comment]
Yes thanks. Have not had achance to reply yet, but it is definately the same as the other one.
