### ISSUE TITLE
Prevent Email validation sending when creating an account from external providers

### ISSUE THREAD

**Issue by Moonsk313** [brockallen/BrockAllen.MembershipReboot#580]
Hi,

We have the following scenario, 
-On login screen, the user can connect himself with facebook.
-authentication facebook
-back from facebook, we create an user in membershipreboot 
-set the email as verified.

But we receive 2 emails, one for validate and the other saying your account is validated.

All looks good except the first email...

Is there a way to prevent sending email for validation?

Thanks

**Comment by brockallen** [comment]
If they're using the external provider workflow then use a different MR config that does not have an email confirmed handler registered.

**Comment by Moonsk313** [comment]
Thanks, it works like a charm!
great work ;)
