### ISSUE TITLE
IdentityServer3, MembershipReboot, MongoDB and Autofac as a selfhosted Windows Service

### ISSUE THREAD

**Issue by windischb** [brockallen/BrockAllen.MembershipReboot#581]
Hi!

Has anybody running all this things together?
Currently i have an IdentityServer3 with Autofac running as a Windows Service.
Now i would like to implement a User Storage with MembershipReboot und MongoDB.
But it won't work... I didn't know how to setup MemberhsipReboot and MongoDB with Autofac.
Are there any Examples or something??

Thanks
Bernhard

**Comment by brockallen** [comment]
Well, IdSvr uses its own DI system so you should look at those samples. https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/MembershipReboot

**Comment by looking-promising** [comment]
@windischb did you figure this out?  We have IdentityServer3+mongodb running with asp.net 5 & MembershipReboot+mongodb.  Much over what we needed was in the samples and some was available as other open source projects.  So, I'm here to say that it can be done.  I'm not sure @brockallen would recommend running with MongoDB (I'm not sure I'd recommend it at this point), it our implementation is fully functional.

If you are stuck or have any specific questions, I may be able to help.

**Comment by brockallen** [comment]
I have no inputs on what DB you should use.
