### ISSUE TITLE
Ninject to autofac?

### ISSUE THREAD

**Issue by cloudybrain** [brockallen/BrockAllen.MembershipReboot#582]
I accidently posted an issue on thinktecture sample collection, when it was really supposed to go here:

https://github.com/IdentityServer/IdentityServer3.Samples/issues/155

Ninject has been causing me some overhead issues and grievances, so in the issue I explained why I went with simpleinjector, but the response to the issue is that all the samples now use autofac. It'd be great to have consistency across the board, especially if I'm using membership reboot and integrating identity server within it.

**Comment by brockallen** [comment]
DI is unrelated to MR -- You'll have to figure out the DI framework you want in your app and understand how configure it. Sorry.
