### ISSUE TITLE
DefaultMembershipRebootDatabase doesn't like the connectionString

### ISSUE THREAD

**Issue by Wesley82** [brockallen/BrockAllen.MembershipReboot#586]
var db = new DefaultMembershipRebootDatabase(this.connString);

I am keep getting this network-related error:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

but the instance name is correct, remote connection is enabled, the same connection string is used in another project and it works fine. Why would this happen, did I miss something?

**Comment by brockallen** [comment]
That's EF giving the error, since MR is just passing along the connection string.

**Comment by Wesley82** [comment]
Thank you very much, Brock!
