### ISSUE TITLE
That mobile phone is already in use by a different account.

### ISSUE THREAD

**Issue by mikeandersun** [brockallen/BrockAllen.MembershipReboot#588]
I try to change mobile phone for a user if the mobile phone is used by another user we have a exception. It is possible to `_userAccountService.ChangeMobilePhoneRequest(userId,phoneNumber );` return a result ?

**Comment by brockallen** [comment]
Does it make sense to allow two accounts to share a mobile phone? Doesn't sound very secure to me.
