### ISSUE TITLE
Using MembershipReboot

### ISSUE THREAD

**Issue by rpundlik** [brockallen/BrockAllen.MembershipReboot#589]
Hello Brock,

We are creating a new mvc applications in which we want to implement SSO functionality.

Basically our requirement is we will call the required methods(Login,Register etc.) of MembershipReboot through web api and will get the response at client side. How can we call these methods through web api ?

Can you please explain how MembershipReboot will play a role here ?

If we use MembershipReboot, then setting up identity server is necessary ?

By looking out into the samples we are not able to figure out which approach is better.

Any help on this appreciated !
Rohit

**Comment by brockallen** [comment]
IdentityServer will give you SSO. Within IdentityServer you will need your user database, and MembershipReboot can manage that piece. As for the many other questions, you should read the docs for IdentityServer.

**Comment by rpundlik** [comment]
Hello Brock,
Thanks for the reply !

Actually after reading the documentation I posted this question. 
As per you answer, It means IdentityServer and MembershipReboot should be in same project ?
If yes, how can I call the MembershipReboot method through web api

Regards,
Rohit

**Comment by brockallen** [comment]
You'd have to build a web api to use MR -- that would be all your code.

**Comment by rpundlik** [comment]
Thanks for the reply Brock,
You mean just like [this](http://stackoverflow.com/questions/27357940/membership-reboot-web-api-controller-async-issue)
