### ISSUE TITLE
Access account from particular claim

### ISSUE THREAD

**Issue by zebamba** [brockallen/BrockAllen.MembershipReboot#591]
Is it possible to get a list of account from same claim?

On my application location is a claim on Users, I need to get a list of
users that belongs to same location / contains particular claim.

Thank you.

**Comment by brockallen** [comment]
There's a IQueryable property on the UserAccountService, or you can hit the DB directly via your DB framework.

**Comment by zebamba** [comment]
Is this method on line 143?
<pre>
 public virtual IUserAccountQuery<TAccount> Query 
</pre>

Thank you.

**Comment by brockallen** [comment]
Yes.

**Comment by zebamba** [comment]
You can close the question.
Thank you.

**Comment by apuchkov** [comment]
Here's an example how to find accounts by particular claim:

```cs
public IEnumerable<UserAccountQueryResult> GetUsersByClaim(string claimType, string claimValue)
{
    return userAccountService.Query.Query(
        users =>
            users.Where(user => user.ClaimCollection.Any(claim => claim.Type == claimType && claim.Value == claimValue)));
}
```

**Comment by kylegalbraith** [comment]
@apuchkov @brockallen I do not seem to have the option to user Query.Query with a lambda inside to talk to the ClaimCollection table....any idea what I am missing?
