### ISSUE TITLE
Adding and removing claims in a transaction

### ISSUE THREAD

**Issue by KathleenDollard** [brockallen/BrockAllen.MembershipReboot#602]
We have a scenario where we are removing claims and adding new ones. If the new ones fail, we'd like to reset to the old ones. Transaction. 

Is there a way to add transaction behavior to Add/Remove claims when going through the API? Or do you suggest bypassing the API and directly touching the Repo/DBContext for this? Or other thoughts. 

Thanks loads!!!!
Kathleen

**Comment by christianacca** [comment]
The `UserAccountService` has the `UpdateClaims` method that takes two collections - one for adding claims the other to remove them. Internally these changes are then saved to the database with a call to `DbContext.SaveChanges` which is itself is transactional.

**Comment by KathleenDollard** [comment]
Sounds perfect. Had overlooked it. Thanks!

**Comment by brockallen** [comment]
Thx @christianacca
