### ISSUE TITLE
Membership Reboot on .NET Core

### ISSUE THREAD

**Issue by AlexandreRoba** [brockallen/BrockAllen.MembershipReboot#608]
Hi Brock,

We are heavily using IdentityServer 3 on Membership Reboot.
We have started looking at IdentityServer 4.0 on .NET Core.
Can you tell me if there are any plan to have .NET Core support for MembershipReboot?

Thanks for the excellent work you have put on this already.

Alex.

**Comment by brockallen** [comment]
Long thread here: https://github.com/brockallen/BrockAllen.MembershipReboot/issues/568
