### ISSUE TITLE
Getting exception 'SessionAuthenticationModule is not configured and it needs to be.'

### ISSUE THREAD

**Issue by rtassarone** [brockallen/BrockAllen.MembershipReboot#609]
I'm getting the exception 'SessionAuthenticationModule is not configured and it needs to be.' upon execution of `authSvc.SignIn` (screenshot attached).

Looking at the source at https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot.WebHost/SamAuthenticationService.cs I see that this exception is thrown when `sam` is null in:

`var sam = FederatedAuthentication.SessionAuthenticationModule;`
`if (sam == null)`
     `// throw...`

The only answer I've seen when Googling is to change from IIS Express (Cassini) to full IIS which seems to not address the issue, not to mention that I tried that and got the same failure.  Any ideas?

![image](https://cloud.githubusercontent.com/assets/16947110/12661862/2624681a-c5ea-11e5-914b-972ba6a9841a.png)

**Comment by brockallen** [comment]
You need to register the SAM HttpModule like this: https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/samples/SingleTenant/SingleTenantWebApp/Web.config#L69

**Comment by rtassarone** [comment]
Terrific thank you Brock...
