### ISSUE TITLE
Question about password expired

### ISSUE THREAD

**Issue by joramwangi** [brockallen/BrockAllen.MembershipReboot#622]
Hello.
I am trying to use the password expired functionality of this library. 
I want the password to be reset whenever expired, however i need to customize the email sent to the user to be specific to password expiry and not use the password reset template.

I cannot find a password expiry event. 
Could you suggest how I can,  within the .IsPasswordExpired(account)
1. Stop the password reset event from firing
2. Trigger a specific email template for password expiry

Any suggestions appreciated

**Comment by brockallen** [comment]
Well, there is no real functionality around password expired -- it's really just a helper to calculate if the password is expired. Your UI would need to check it and enforce it in some way.

**Comment by joramwangi** [comment]
Is there a way to call  passwordreset but but not trigger the password
reset event

**Comment by brockallen** [comment]
If you don't care about the event, then don't register a handler for the event.
