### ISSUE TITLE
UserAccountService.ChangeEmailRequest does not update UserAccounts.Username when EmailIsUsername is True 

### ISSUE THREAD

**Issue by jonbarthol** [brockallen/BrockAllen.MembershipReboot#626]
BrockAllen, I noticed today what appears to be bug in UserAccountService.ChangeEmailRequest. If Configuration.EmailIsUsername is set to True, I would think that ChangeEmailRequest should update the Username in addition to the email address. Is there another way to update the Username? The ChangeUsername method gives the following error when I try to use it:
"[UserAccountService.ChangeUsername] failed -- SecuritySettings.EmailIsUsername is true, use ChangeEmail API instead." Thanks.

**Comment by brockallen** [comment]
I think that's done when the email is confirmed (IIRC)

**Comment by jonbarthol** [comment]
Ok. That makes sense. Thanks.
