### ISSUE TITLE
MembershipReboot  for ASP.NET Core 1.0

### ISSUE THREAD

**Issue by OscarAgreda** [brockallen/BrockAllen.MembershipReboot#628]
Hello Brock Allen, any plans to create this user identity management and authentication library for for ASP.NET Core 1.0.

In the same mentality that drove your team to develop Identity Server 4 to be purely for ASP.NET Core 1.0

**Comment by brockallen** [comment]
Not sure yet. See this thread: https://github.com/brockallen/BrockAllen.MembershipReboot/issues/568
