### ISSUE TITLE
Any way to use BCrypt instead of the default hashing method?

### ISSUE THREAD

**Issue by ZBlocker655** [brockallen/BrockAllen.MembershipReboot#629]
Evaluating this framework for use in a new service my team is working on.  Is there any way to swap out the password hash method and use BCrypt instead?  It seems to be a slightly stronger method than PBKDF2. 

If not, would you recommend I instead look at IdentityReboot over ASP.NET Identity if I need BCrypt?

**Comment by brockallen** [comment]
There's an ICrypto interface you can plug in.

**Comment by brockallen** [comment]
BTW, do you have a bcrypt implementation in .NET? If so I'd be interested.

**Comment by ZBlocker655** [comment]
You mean an implementation of your `ICrypt` interface that uses BCrypt?  Not yet, since I just found out about it.  Are you saying that if I end up writing one you'd be interested in adding it to this framework?

**Comment by brockallen** [comment]
No, I was just asking which bcrypt library you were using. But yea, if you do an ICrytpo using it, let me know. I'm interested in both :)

**Comment by ZBlocker655** [comment]
I might end up using BCrypt.Net.   Not sure yet.  Still in evaluation phase.

**Comment by brockallen** [comment]
Any update on finding a good .NET based bcrypt?

**Comment by ZBlocker655** [comment]
Still discussing with my team whether we need to put in BCrypt hashing or not.  So far we're using the default for MembershipReboot.  If we do go BCrypt, we'll probably use [BCrypt.Net](https://bcrypt.codeplex.com/).

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
