### ISSUE TITLE
New AccountUnlockedEvent

### ISSUE THREAD

**Issue by ccrowhurstram** [brockallen/BrockAllen.MembershipReboot#630]
Hi Brok,

Are you ok with me adding a new event - `AccountUnlockedEvent`.

This event would be raised when `UserAccountService.SetIsLoginAllowed` is called with an `isLoginAllowed` argument set to `true` (and the account is currently locked).

Thanks
C

**Comment by brockallen** [comment]
Sure.

**Comment by christianacca** [comment]
Just merged :-)

**Comment by ccrowhurstram** [comment]
Actually, I've got more changes I think that need to be added. See PR: https://github.com/brockallen/BrockAllen.MembershipReboot/pull/631
