### ISSUE TITLE
Change Email captures account verified event

### ISSUE THREAD

**Issue by skbelalmd** [brockallen/BrockAllen.MembershipReboot#637]
Hai brock,
When I change the email using userAccountService.ChangeEmailRequest(accountId,newEmail),it captures the email verified event instead of email changed event.

the problem persists even if I defined the EmailChangeRequested Event.

**Comment by brockallen** [comment]
IIRC, I think it depends on the state of the user account -- take a look at the code to see why (i don't recall off the top of my head).

**Comment by skbelalmd** [comment]
The user account is verified.

Can you please share the exact portion of the code where I should look.
