### ISSUE TITLE
Method not found: 'System.__Canon BrockAllen.MembershipReboot.UserAccountService`1.CreateAccount

### ISSUE THREAD

**Issue by vinaykasireddy** [brockallen/BrockAllen.MembershipReboot#639]
I am receiving the below error. Any idea on what might be the cause?  I get this error message only when i try to create a user using identity manager new user page.

Version Installed:

IdentityServer3 2.5
BrockAllen.MembershipReboot 8.4
IdentityServer3.MembershipReboot 2.0
IdentityManager.MembershipReboot 1.0.0-beta5 (Prerelease)
IdentityManager 1.0.0-beta5-4 (Prerelease)

![image](https://cloud.githubusercontent.com/assets/2632995/14786956/f0c62b6a-0b33-11e6-82ca-0f6c8c301112.png)

![image](https://cloud.githubusercontent.com/assets/2632995/14786737/cd6a4e04-0b32-11e6-93cb-dce9fc2632aa.png)

**Comment by brockallen** [comment]
Yea, I think I've seen this before when there's some version mismatch. Are all the nugets up to date.

**Comment by vinaykasireddy** [comment]
Yes. I tried in all the combinations unless u want me to downgrade everything, which is not possible.

You might have seen the similar issue at the below link. I even replied the same thing there but no support. Thought it will be rectified by now and upgraded everything to latest. But still the problem exists.

https://github.com/IdentityServer/IdentityServer3/issues/1790

**Comment by mafshin** [comment]
Thanks @brockallen , I faced the very same exception and as you suggested it was because of version mismatch. The `Consolidate `option in `Nuget Package Manager` fixed that.
