### ISSUE TITLE
Allow non-unique mobile phones.

### ISSUE THREAD

**Issue by mirecg** [brockallen/BrockAllen.MembershipReboot#657]
This issue is similar to #645. 

In our existing solution the customers have several accounts with same certificate and with the same phone number. In order to migrate our solution of identity model to MBR, I need the configuration support for this.
I would create MobilePhoneIsUnique configuration property for this.

**Comment by brockallen** [comment]
Sorry, I don't have the bandwidth to try to make this change.

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
