### ISSUE TITLE
GetValidationMessage wrong culture

### ISSUE THREAD

**Issue by lgoudriaan** [brockallen/BrockAllen.MembershipReboot#668]
when i call userAccountService.GetValidationMessage(code) it returns the English message, but my current culture is 'nl'.

Any ideas how to fix this?

**Comment by brockallen** [comment]
Hmm, not sure -- debug into it. Looks like there's a nl-nl resx, so maybe it would be better to just rename it to nl.

**Comment by jonbarthol** [comment]
@lgoudriaan: Did you ever resolve this? I think I'm having a similar issue. See issue #670. Thanks!

**Comment by lgoudriaan** [comment]
No, sorry I haven't looked in it yet.

**Comment by lgoudriaan** [comment]
I finally had time to look into this.
I found out that the project uses the Satellite Package Approach and those packages aren't released in NuGet.

@brockallen can you publish these packages? or maybe switch to the Single Package Approach it wil only add Kb for each language

**Comment by brockallen** [comment]
If you can propose a PR to merge it all into one, I'm happy with that.
