### ISSUE TITLE
Trouble getting ValidationMessages translated

### ISSUE THREAD

**Issue by jonbarthol** [brockallen/BrockAllen.MembershipReboot#670]
This looks like it could be related to issue #668.

I can't figure out how to get ValidationMessages in a language other than English. I set my culture to "de" (German) in my Web.config. I also tried setting the culture in my startup and controller classes by setting Thread.CurrentThread.CurrentCulture and Thread.CurrentThread.CurrentUICulture. We have our own custom messages which are translating fine into German, so the Web.config setting is certainly driving something.

I also tried setting ValidationMessages.Culture = CultureInfo.GetCultureInfo("de"), but that didn't work either. Do I need to download satellite packages for each language? The satellite packages don't seem to be published.

Any ideas? Thanks!

**Comment by jonbarthol** [comment]
I also tried setting ValidationMessages.Culture = CultureInfo.GetCultureInfo("de"), but that didn't work either.

**Comment by lgoudriaan** [comment]
@jonbarthol Did you use the NuGet packages?

**Comment by jonbarthol** [comment]
@lgoudriaan which NuGet packages are your referring to? I just have the BrockAllen.MembershipReboot version 8.4.0 package. No other package has been released.

**Comment by brockallen** [comment]
9.0.0 was released and the translations should now be with the one package

**Comment by jonbarthol** [comment]
Thanks, @brockallen !
