### ISSUE TITLE
Attempting to create user with existing email issue - (bug?)

### ISSUE THREAD

**Issue by Steven-Pingel** [brockallen/BrockAllen.MembershipReboot#673]
1) Attempt to create a new UserAccount with email in use
2) Receive validation error (correct behavior)
3) Correct the validation issue by inputting an unused email address.
4) First email (the one already in use) receives the confirmation email with the original invalid request's details (Bug).

Current thought (please correct me if I'm wrong) is that an account created event is being pushed prior to the email validation.

Specifically in `UserAccountService.Init` which is called on ln459 prior to the `ValidateEmail` call on ln462.
https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/AccountService/UserAccountService.cs#L545

**Comment by brockallen** [comment]
Ah quite possibly. If you feel like helping out, you could write a unit test to show that it's broken. That way when it's fixed, we have a test to show it's fixed (forever).

**Comment by Steven-Pingel** [comment]
> If you feel like helping out, you could write a unit test to show that it's broken.

I'm looking into that now actually.  Enjoy your holiday!

**Comment by Steven-Pingel** [comment]
I created a branch on my fork to demonstrate the failure condition.  Here's the diff, not quite ready to open a PR on this yet but open to discussion on a possible fix.

https://github.com/brockallen/BrockAllen.MembershipReboot/compare/master...Steven-Pingel:bugUnitTest?expand=1

**Comment by brockallen** [comment]
Any update?

**Comment by Steven-Pingel** [comment]
No, we've actually forked this project locally, I'll update if/when we fix it.  I need to get a more robust test in place to prove the issue, as it seems to work when tested in the context of the user service.  Point still stands though that it's a bit odd the created event is pushed into the queue prior to the validation calls.
