### ISSUE TITLE
Best practice for Key/ID

### ISSUE THREAD

**Issue by TDK1964** [brockallen/BrockAllen.MembershipReboot#674]
All my tables have 2 audit fields DateModified and ModifiedBy. My question is should the ModifiedBy type be an int or a Guid?
My initial thoughts where it should be the guid because HttpContext.Current.User.GetUserID() return a guid.

**Comment by brockallen** [comment]
Depends. Are the users doing the modification from the same system? Use whatever makes sense for your system. The GUID is the unique identifier for the user. The int is just a DB index/key.
