### ISSUE TITLE
Publish to Shared host

### ISSUE THREAD

**Issue by amirhp** [brockallen/BrockAllen.MembershipReboot#676]
Hi thanks for such a great product!
I need to publish my site to shared host set Load User Profile to false which is need to be true in memberhsipreboot is there any solution for publishing it in shared hosts.
Regards
Amir

**Comment by brockallen** [comment]
Why does LoadUserProfile need to be true?

**Comment by amirhp** [comment]
Raise an error otherwise there is an issue for this before.
https://github.com/brockallen/BrockAllen.MembershipReboot/issues/55

**Comment by brockallen** [comment]
Right, so same as the other issue -- this is not a MR issue, it's a WIF issue.

**Comment by amirhp** [comment]
:) yeah do you know any way to work around?

**Comment by brockallen** [comment]
To be honest I've forgotten what the original reason in WIF was... so no, i don't have an answer off the top of my head. Sorry.
