### ISSUE TITLE
Account Verification

### ISSUE THREAD

**Issue by pmbanugo** [brockallen/BrockAllen.MembershipReboot#678]
I don't want some users to get an account verification email. I want to automatically from code, mark their account as verified.

**Comment by brockallen** [comment]
Yes, that's possible as well. You use a different MR config for those scenarios (where an email notification is not registered). Also, there's an API to mark an email as verified.

**Comment by pmbanugo** [comment]
Ok. The one of a different MR config I can get around by, but I can't seem to find an API to mark the user's account as verified. Please note, that I want this to be done at users account creation without sending email.

**Comment by brockallen** [comment]
https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/AccountService/UserAccountService.cs#L1870

**Comment by pmbanugo** [comment]
Thanks. will try that out now.
