### ISSUE TITLE
MembershipRebootDbContext ignores my connection string

### ISSUE THREAD

**Issue by mafshin** [brockallen/BrockAllen.MembershipReboot#680]
I have a class like this:

```
public class MyContext: BrockAllen.MembershipReboot.Ef.MembershipRebootDbContext<MyUserAccount>
{
        public MyContext(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }
}
```

When I try to construct `MyContext` (and create database files) via the specified constructor passing the following connectionString:

```
Data Source=.\SQLExpress2012;AttachDbFilename=E:\db.mdf;Initial Catalog=db;Integrated Security=True;MultipleActiveResultSets=True
```

Membership completely ignored my connection string and changed it to the following value:

```
Data Source=.\SQLEXPRESS;Initial Catalog=MembershipReboot;Integrated Security=True;MultipleActiveResultSets=True
```

What went wrong?

**Comment by mafshin** [comment]
No idea on this? A `MembershipReboot` database is created when I want to initialize my db!!

**Comment by brockallen** [comment]
search the issues -- this has been discussed before
