### ISSUE TITLE
Combining various samples into one all conquering sample

### ISSUE THREAD

**Issue by TDK1964** [brockallen/BrockAllen.MembershipReboot#681]
Hi Brock,

I'm really struggling to get the following samples all working together. Is there any chance you could create another sample combining all the following?

CustomizationsSample 
SingleTenantOwinSystemWeb
IdentityManager.MembershipReboot
Autofac

**Comment by brockallen** [comment]
Given that I don't foresee making this change, I'll close this issue. Thanks.
