### ISSUE TITLE
Should I set authentication mode to forms or None?

### ISSUE THREAD

**Issue by pmbanugo** [brockallen/BrockAllen.MembershipReboot#682]
Should I set authentication mode to forms or None? If I set to none  then it doesn't get redirected to my login page. what is the best approach to this?

**Comment by brockallen** [comment]
Are you using WIF or Katana for your cookie management?

**Comment by pmbanugo** [comment]
I'm using WIF

**Comment by brockallen** [comment]
Well, you can set it to None, but then no redirects happen to your login page (as you saw). IIRC, you can still the forms auth redirect and it will kick in and redirect your users (even though you're not using forms auth for actually logging in the users). The other option is to build a module to redirect on a 401 response.

**Comment by pmbanugo** [comment]
ok. I have the auth mode set to forms in-which it redirects to the correct page.

I'm trying to set sliding expiration. I tried using the forms auth method (which I know wouldn't work) and now I saw some resources online, but with the implementation I have, user is automatically logged out after set time, in other words, absolute expiration is what I have working and I want a sliding expiration. Please point me in the right direction. 
Below is my web.config setting:

```xml

 <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="false" persistentSessionLifetime="00:20:00" />
    </federationConfiguration>
  </system.identityModel.services>
  <system.identityModel>
    <identityConfiguration>
      <securityTokenHandlers>
          <remove type="System.IdentityModel.Tokens.SessionSecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral,                     PublicKeyToken=B77A5C561934E089" />

        <add type="System.IdentityModel.Tokens.SessionSecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral,                  PublicKeyToken=B77A5C561934E089">
          <sessionTokenRequirement lifetime="00:20:00"></sessionTokenRequirement>
        </add>
      </securityTokenHandlers>
    </identityConfiguration>
  </system.identityModel>

```

**Comment by pmbanugo** [comment]
Ok thanks
