### ISSUE TITLE
Account Creation Email

### ISSUE THREAD

**Issue by vjkr14** [brockallen/BrockAllen.MembershipReboot#690]
Hello Brock,
Great work!!.
I am new to this dot net and trying to learn identity framework, stuck configuring email using membership reboot sample code. 

Have added smtp details in web.config file, on account creation want to send mail to user to verify the account, but don't know how to do. using email events. below code is working but not standard/OOTB Functionality. 

```
SmtpMessageDelivery de = new SmtpMessageDelivery();
Message msg = new Message();
msg.To = account.Email;
msg.Subject = "Acoount";
msg.Body = "tst";
de.Send(msg);
```

Googled it but not getting sufficient references from there.

Request if you can help me with step by step documentation of membership reboot, atleast expecting sending mail on account creation/updation of email etc....

Thanks in Advance. 
Regards,
Vijay Kumar Singh

**Comment by vjkr14** [comment]
Any body else can help?

**Comment by brockallen** [comment]
the wiki is about all there is (beyond the samples). sorry.
