### ISSUE TITLE
SignIn works fine - SignOut tosses: Cannot

### ISSUE THREAD

**Issue by justSteve** [brockallen/BrockAllen.MembershipReboot#691]
I'm hitting some strangeness on a project that's been running against MR since early days. Somewhere between my last deploy and my current codebase, the ability to log a user out broke. I can sign in but any attempt to call the  _samAuthenticationService.SignOut(); are being met with: Unable to connect to SQL Server database.

Any thoughts on how could it be that the db is found for SignIn but not for SignOut?

thx

**Comment by brockallen** [comment]
Hmm, not sure. More info needed I think.
