### ISSUE TITLE
 NuGet package: MembershipReboot 9.0.0 does not fit MembershipReboot.Webhost 7.1.0

### ISSUE THREAD

**Issue by GeertVeenstra** [brockallen/BrockAllen.MembershipReboot#693]
If I install the 9.0.0 NuGet version I get a TypeLoadException because the GetCurrentPrincipal does not exist in the WebHost package.
Instead it is named GetCurentPrincipal.

In the source code I see this was renamed a long time ago ?

Regards,

Geert Veenstra

**Comment by brockallen** [comment]
yes, 9.0 was expected to contain some breaking changes. you can submit a PR for the web host if you'd like.
