### ISSUE TITLE
what is Groups, is it an implementation of hierarchical roles?

### ISSUE THREAD

**Issue by ashkansk** [brockallen/BrockAllen.MembershipReboot#91]
In your new sample projects I noticed an example that creates Groups and GroupChild tables which were not present in previous code. however the sample does not allow to create a child group, I was wondering if this is for supporting hierarchical roles or not ?

If not, what's the purpose of these two tables added to the project?

**Comment by kishorkadam** [comment]
Hi Brock, I am using MR in my project . May I know  what way are Groups related to USER if Groups are different than ROLES .
Also, what information can be stored in Groups and Group Child.

**Comment by brockallen** [comment]
Groups are just a named set of claims.
